### ISSUE TITLE
Protocol error Browser.close: Target closed

### ISSUE THREAD

**Issue by fushall** [pyppeteer/pyppeteer#104]
My development environment is win10 with python3.7.6 and  pyppeteer2 of pup2.1.1 branch
There was an excpetion raised when  I tried to run the below code.
(If I pass `headless=False` to `launch`, the exception doesn't be raised)
Finally I read this https://github.com/miyakogi/pyppeteer/issues/171#issuecomment-609429651   and some relevant issues, but I still have no idea how to fix the issue.

```python
import asyncio
from pyppeteer import launch

async def main():
    browser = await launch(userDataDir=r'c:\temp')
    page = await browser.newPage()
    await page.goto('https://example.com')
    await browser.close()


asyncio.get_event_loop().run_until_complete(main())

```

```plaintext
Transport connection closed: code = 1006 (connection closed abnormally [internal]), no reason
Traceback (most recent call last):
  File "D:/workspace/sthq/htmlspider/main.py", line 13, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "D:\Program Files\Python37\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "D:/workspace/sthq/htmlspider/main.py", line 10, in main
    await browser.close()
  File "D:\venv\htmlspider\lib\site-packages\pyppeteer\browser.py", line 275, in close
    await self._closeCallback()
  File "D:\venv\htmlspider\lib\site-packages\pyppeteer\launcher.py", line 128, in close
    return await self._close_proc()
  File "D:\venv\htmlspider\lib\site-packages\pyppeteer\launcher.py", line 103, in _close_proc
    await self.connection.send('Browser.close')
pyppeteer.errors.NetworkError: Protocol error Browser.close: Target closed.
```

**Comment by Mattwmaster58** [comment]
Can you attach a streamhandler to the pyppeteer logging stream and set the level to debug?

**Comment by fushall** [comment]
> Can you attach a streamhandler to the pyppeteer logging stream and set the level to debug?

These are all debug logs. 

```plaintext
D:\venv\pyppeteer2_demo\Scripts\python.exe D:/workspace/pyppeteer2_demo/main.py --log debug
platform auto detected: win64
Calling process: C:\Users\Administrator\AppData\Local\pyppeteer\pyppeteer\local-chromium\win64-722234\chrome-win\chrome.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=c:\temp --headless --hide-scrollbars --mute-audio about:blank --remote-debugging-port=58375
SEND ▶ {"method": "Target.setDiscoverTargets", "params": {"discover": true}, "id": 1}
◀ RECV {'method': 'Target.targetCreated', 'params': {'targetInfo': {'targetId': '1aadff51-17c3-4877-bd4a-7b121c3f29e0', 'type': 'browser', 'title': '', 'url': '', 'attached': True}}}
◀ RECV {'method': 'Target.targetCreated', 'params': {'targetInfo': {'targetId': '94e7fb40-3e8d-4343-8a1a-9d57dbca9048', 'type': 'browser', 'title': '', 'url': '', 'attached': False}}}
◀ RECV {'method': 'Target.targetCreated', 'params': {'targetInfo': {'targetId': 'C8CC9ABD164F6E27084032B3D95CA731', 'type': 'page', 'title': '', 'url': 'about:blank', 'attached': False, 'browserContextId': 'DB95B3F70EC5CFB986E19C63894474BE'}}}
◀ RECV {'id': 1, 'result': {}}
SEND ▶ {"method": "Target.createTarget", "params": {"url": "about:blank"}, "id": 2}
◀ RECV {'method': 'Target.targetCreated', 'params': {'targetInfo': {'targetId': 'B7E45D9F0E31A48BEBE4009D750665B0', 'type': 'page', 'title': '', 'url': '', 'attached': False, 'browserContextId': 'DB95B3F70EC5CFB986E19C63894474BE'}}}
◀ RECV {'id': 2, 'result': {'targetId': 'B7E45D9F0E31A48BEBE4009D750665B0'}}
◀ RECV {'method': 'Target.targetInfoChanged', 'params': {'targetInfo': {'targetId': 'B7E45D9F0E31A48BEBE4009D750665B0', 'type': 'page', 'title': 'about:blank', 'url': 'about:blank', 'attached': False, 'browserContextId': 'DB95B3F70EC5CFB986E19C63894474BE'}}}
◀ RECV {'method': 'Target.targetInfoChanged', 'params': {'targetInfo': {'targetId': 'C8CC9ABD164F6E27084032B3D95CA731', 'type': 'page', 'title': 'about:blank', 'url': 'about:blank', 'attached': False, 'browserContextId': 'DB95B3F70EC5CFB986E19C63894474BE'}}}
SEND ▶ {"method": "Target.attachToTarget", "params": {"targetId": "B7E45D9F0E31A48BEBE4009D750665B0", "flatten": true}, "id": 3}
◀ RECV {'method': 'Target.targetInfoChanged', 'params': {'targetInfo': {'targetId': 'B7E45D9F0E31A48BEBE4009D750665B0', 'type': 'page', 'title': 'about:blank', 'url': 'about:blank', 'attached': True, 'browserContextId': 'DB95B3F70EC5CFB986E19C63894474BE'}}}
◀ RECV {'method': 'Target.attachedToTarget', 'params': {'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB', 'targetInfo': {'targetId': 'B7E45D9F0E31A48BEBE4009D750665B0', 'type': 'page', 'title': 'about:blank', 'url': 'about:blank', 'attached': True, 'browserContextId': 'DB95B3F70EC5CFB986E19C63894474BE'}, 'waitingForDebugger': False}}
◀ RECV {'id': 3, 'result': {'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}}
SEND ▶ {"sessionId": "4C62C2F5EBAEA12927C072E8FE976EAB", "method": "Target.setAutoAttach", "params": {"autoAttach": true, "waitForDebuggerOnStart": false, "flatten": true}, "id": 4}
SEND ▶ {"sessionId": "4C62C2F5EBAEA12927C072E8FE976EAB", "method": "Performance.enable", "params": {}, "id": 5}
SEND ▶ {"sessionId": "4C62C2F5EBAEA12927C072E8FE976EAB", "method": "Log.enable", "params": {}, "id": 6}
SEND ▶ {"sessionId": "4C62C2F5EBAEA12927C072E8FE976EAB", "method": "Page.enable", "params": {}, "id": 7}
◀ RECV {'id': 4, 'result': {}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'id': 5, 'result': {}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'id': 6, 'result': {}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'id': 7, 'result': {}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
SEND ▶ {"sessionId": "4C62C2F5EBAEA12927C072E8FE976EAB", "method": "Page.getFrameTree", "params": {}, "id": 8}
◀ RECV {'id': 8, 'result': {'frameTree': {'frame': {'id': 'B7E45D9F0E31A48BEBE4009D750665B0', 'loaderId': 'C8825932B6424CFA083C3BD1891867F5', 'url': 'about:blank', 'securityOrigin': '://', 'mimeType': 'text/html'}}}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
SEND ▶ {"sessionId": "4C62C2F5EBAEA12927C072E8FE976EAB", "method": "Page.setLifecycleEventsEnabled", "params": {"enabled": true}, "id": 9}
SEND ▶ {"sessionId": "4C62C2F5EBAEA12927C072E8FE976EAB", "method": "Runtime.enable", "params": {}, "id": 10}
SEND ▶ {"sessionId": "4C62C2F5EBAEA12927C072E8FE976EAB", "method": "Network.enable", "params": {}, "id": 11}
◀ RECV {'method': 'Page.lifecycleEvent', 'params': {'frameId': 'B7E45D9F0E31A48BEBE4009D750665B0', 'loaderId': 'C8825932B6424CFA083C3BD1891867F5', 'name': 'commit', 'timestamp': 184547.187219}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Page.lifecycleEvent', 'params': {'frameId': 'B7E45D9F0E31A48BEBE4009D750665B0', 'loaderId': 'C8825932B6424CFA083C3BD1891867F5', 'name': 'DOMContentLoaded', 'timestamp': 184547.18727}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Page.lifecycleEvent', 'params': {'frameId': 'B7E45D9F0E31A48BEBE4009D750665B0', 'loaderId': 'C8825932B6424CFA083C3BD1891867F5', 'name': 'load', 'timestamp': 184547.187488}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Page.lifecycleEvent', 'params': {'frameId': 'B7E45D9F0E31A48BEBE4009D750665B0', 'loaderId': 'C8825932B6424CFA083C3BD1891867F5', 'name': 'networkAlmostIdle', 'timestamp': 184547.188047}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Page.lifecycleEvent', 'params': {'frameId': 'B7E45D9F0E31A48BEBE4009D750665B0', 'loaderId': 'C8825932B6424CFA083C3BD1891867F5', 'name': 'networkIdle', 'timestamp': 184547.188047}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'id': 9, 'result': {}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Runtime.executionContextCreated', 'params': {'context': {'id': 1, 'origin': '://', 'name': '', 'auxData': {'isDefault': True, 'type': 'default', 'frameId': 'B7E45D9F0E31A48BEBE4009D750665B0'}}}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'id': 10, 'result': {}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'id': 11, 'result': {}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
SEND ▶ {"sessionId": "4C62C2F5EBAEA12927C072E8FE976EAB", "method": "Page.addScriptToEvaluateOnNewDocument", "params": {"source": "//# sourceURL=__puppeteer_evaluation_script__", "worldName": "__puppeteer_utility_world__"}, "id": 12}
◀ RECV {'id': 12, 'result': {'identifier': '1'}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
SEND ▶ {"sessionId": "4C62C2F5EBAEA12927C072E8FE976EAB", "method": "Page.createIsolatedWorld", "params": {"frameId": "B7E45D9F0E31A48BEBE4009D750665B0", "grantUniversalAccess": true, "worldName": "__puppeteer_utility_world__"}, "id": 13}
◀ RECV {'method': 'Runtime.executionContextCreated', 'params': {'context': {'id': 2, 'origin': '', 'name': '__puppeteer_utility_world__', 'auxData': {'isDefault': False, 'type': 'isolated', 'frameId': 'B7E45D9F0E31A48BEBE4009D750665B0'}}}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'id': 13, 'result': {'executionContextId': 2}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
SEND ▶ {"sessionId": "4C62C2F5EBAEA12927C072E8FE976EAB", "method": "Emulation.setDeviceMetricsOverride", "params": {"mobile": false, "width": 800, "height": 600, "deviceScaleFactor": 1, "screenOrientation": {"angle": 0, "type": "portraitPrimary"}}, "id": 14}
SEND ▶ {"sessionId": "4C62C2F5EBAEA12927C072E8FE976EAB", "method": "Emulation.setTouchEmulationEnabled", "params": {"enabled": false}, "id": 15}
◀ RECV {'id': 14, 'result': {}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'id': 15, 'result': {}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
SEND ▶ {"sessionId": "4C62C2F5EBAEA12927C072E8FE976EAB", "method": "Page.navigate", "params": {"url": "https://example.com", "referrer": "", "frameId": "B7E45D9F0E31A48BEBE4009D750665B0"}, "id": 16}
◀ RECV {'method': 'Network.requestWillBeSent', 'params': {'requestId': '707685A21C04DB6D5852121F016011EC', 'loaderId': '707685A21C04DB6D5852121F016011EC', 'documentURL': 'https://example.com/', 'request': {'url': 'https://example.com/', 'method': 'GET', 'headers': {'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/80.0.3987.0 Safari/537.36', 'Sec-Fetch-Dest': 'document'}, 'mixedContentType': 'none', 'initialPriority': 'VeryHigh', 'referrerPolicy': 'no-referrer-when-downgrade'}, 'timestamp': 184547.224717, 'wallTime': 1589297958.391839, 'initiator': {'type': 'other'}, 'type': 'Document', 'frameId': 'B7E45D9F0E31A48BEBE4009D750665B0', 'hasUserGesture': False}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Network.responseReceivedExtraInfo', 'params': {'requestId': '707685A21C04DB6D5852121F016011EC', 'blockedCookies': [], 'headers': {'status': '200', 'content-encoding': 'gzip', 'age': '367988', 'cache-control': 'max-age=604800', 'content-type': 'text/html; charset=UTF-8', 'date': 'Tue, 12 May 2020 07:04:13 GMT', 'etag': '"3147526947+gzip"', 'expires': 'Tue, 19 May 2020 07:04:13 GMT', 'last-modified': 'Thu, 17 Oct 2019 07:18:26 GMT', 'server': 'ECS (sjc/4E74)', 'vary': 'Accept-Encoding', 'x-cache': 'HIT', 'content-length': '648'}}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Network.responseReceived', 'params': {'requestId': '707685A21C04DB6D5852121F016011EC', 'loaderId': '707685A21C04DB6D5852121F016011EC', 'timestamp': 184547.254726, 'type': 'Document', 'response': {'url': 'https://example.com/', 'status': 200, 'statusText': '', 'headers': {'status': '200', 'content-encoding': 'gzip', 'age': '367988', 'cache-control': 'max-age=604800', 'content-type': 'text/html; charset=UTF-8', 'date': 'Tue, 12 May 2020 07:04:13 GMT', 'etag': '"3147526947+gzip"', 'expires': 'Tue, 19 May 2020 07:04:13 GMT', 'last-modified': 'Thu, 17 Oct 2019 07:18:26 GMT', 'server': 'ECS (sjc/4E74)', 'vary': 'Accept-Encoding', 'x-cache': 'HIT', 'content-length': '648'}, 'mimeType': 'text/html', 'connectionReused': False, 'connectionId': 0, 'remoteIPAddress': '127.0.0.1', 'remotePort': 12333, 'fromDiskCache': True, 'fromServiceWorker': False, 'fromPrefetchCache': False, 'encodedDataLength': 0, 'timing': {'requestTime': 184547.227512, 'proxyStart': -1, 'proxyEnd': -1, 'dnsStart': -1, 'dnsEnd': -1, 'connectStart': -1, 'connectEnd': -1, 'sslStart': -1, 'sslEnd': -1, 'workerStart': -1, 'workerReady': -1, 'sendStart': 23.268, 'sendEnd': 23.268, 'pushStart': 0, 'pushEnd': 0, 'receiveHeadersEnd': 26.413}, 'protocol': 'h2', 'securityState': 'secure', 'securityDetails': {'protocol': 'TLS 1.3', 'keyExchange': '', 'keyExchangeGroup': 'P-256', 'cipher': 'AES_256_GCM', 'certificateId': 0, 'subjectName': 'www.example.org', 'sanList': ['www.example.org', 'example.com', 'example.edu', 'example.net', 'example.org', 'www.example.com', 'www.example.edu', 'www.example.net'], 'issuer': 'DigiCert SHA2 Secure Server CA', 'validFrom': 1543363200, 'validTo': 1606910400, 'signedCertificateTimestampList': [], 'certificateTransparencyCompliance': 'unknown'}}, 'frameId': 'B7E45D9F0E31A48BEBE4009D750665B0'}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'id': 16, 'result': {'frameId': 'B7E45D9F0E31A48BEBE4009D750665B0', 'loaderId': '707685A21C04DB6D5852121F016011EC'}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Target.targetInfoChanged', 'params': {'targetInfo': {'targetId': 'B7E45D9F0E31A48BEBE4009D750665B0', 'type': 'page', 'title': 'https://example.com', 'url': 'https://example.com/', 'attached': True, 'browserContextId': 'DB95B3F70EC5CFB986E19C63894474BE'}}}
◀ RECV {'method': 'Page.frameStartedLoading', 'params': {'frameId': 'B7E45D9F0E31A48BEBE4009D750665B0'}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Page.lifecycleEvent', 'params': {'frameId': 'B7E45D9F0E31A48BEBE4009D750665B0', 'loaderId': '707685A21C04DB6D5852121F016011EC', 'name': 'init', 'timestamp': 184547.256895}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Runtime.executionContextDestroyed', 'params': {'executionContextId': 1}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Runtime.executionContextDestroyed', 'params': {'executionContextId': 2}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Runtime.executionContextsCleared', 'params': {}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Page.frameNavigated', 'params': {'frame': {'id': 'B7E45D9F0E31A48BEBE4009D750665B0', 'loaderId': '707685A21C04DB6D5852121F016011EC', 'url': 'https://example.com/', 'securityOrigin': 'https://example.com', 'mimeType': 'text/html'}}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Runtime.executionContextCreated', 'params': {'context': {'id': 3, 'origin': 'https://example.com', 'name': '', 'auxData': {'isDefault': True, 'type': 'default', 'frameId': 'B7E45D9F0E31A48BEBE4009D750665B0'}}}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Runtime.executionContextCreated', 'params': {'context': {'id': 4, 'origin': '://', 'name': '__puppeteer_utility_world__', 'auxData': {'isDefault': False, 'type': 'isolated', 'frameId': 'B7E45D9F0E31A48BEBE4009D750665B0'}}}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Network.dataReceived', 'params': {'requestId': '707685A21C04DB6D5852121F016011EC', 'timestamp': 184547.263632, 'dataLength': 1256, 'encodedDataLength': 0}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Network.loadingFinished', 'params': {'requestId': '707685A21C04DB6D5852121F016011EC', 'timestamp': 184547.254761, 'encodedDataLength': 0, 'shouldReportCorbBlocking': False}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Page.domContentEventFired', 'params': {'timestamp': 184547.265556}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Page.lifecycleEvent', 'params': {'frameId': 'B7E45D9F0E31A48BEBE4009D750665B0', 'loaderId': '707685A21C04DB6D5852121F016011EC', 'name': 'DOMContentLoaded', 'timestamp': 184547.265556}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Page.loadEventFired', 'params': {'timestamp': 184547.265731}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Page.lifecycleEvent', 'params': {'frameId': 'B7E45D9F0E31A48BEBE4009D750665B0', 'loaderId': '707685A21C04DB6D5852121F016011EC', 'name': 'load', 'timestamp': 184547.265731}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
◀ RECV {'method': 'Page.frameStoppedLoading', 'params': {'frameId': 'B7E45D9F0E31A48BEBE4009D750665B0'}, 'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB'}
SEND ▶ {"method": "Browser.close", "params": {}, "id": 17}
◀ RECV {'id': 17, 'result': {}}
SEND ▶ {"method": "Browser.close", "params": {}, "id": 18}
◀ RECV {'method': 'Target.targetInfoChanged', 'params': {'targetInfo': {'targetId': 'B7E45D9F0E31A48BEBE4009D750665B0', 'type': 'page', 'title': 'Example Domain', 'url': 'https://example.com/', 'attached': False, 'browserContextId': 'DB95B3F70EC5CFB986E19C63894474BE'}}}
◀ RECV {'method': 'Target.detachedFromTarget', 'params': {'sessionId': '4C62C2F5EBAEA12927C072E8FE976EAB', 'targetId': 'B7E45D9F0E31A48BEBE4009D750665B0'}}
◀ RECV {'method': 'Target.targetDestroyed', 'params': {'targetId': 'B7E45D9F0E31A48BEBE4009D750665B0'}}
◀ RECV {'method': 'Target.targetDestroyed', 'params': {'targetId': 'C8CC9ABD164F6E27084032B3D95CA731'}}
Transport connection closed: code = 1006 (connection closed abnormally [internal]), no reason
Disposing connection: code=1000 reason=
Traceback (most recent call last):
  File "D:/workspace/pyppeteer2_demo/main.py", line 14, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "D:\Program Files\Python37\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "D:/workspace/pyppeteer2_demo/main.py", line 11, in main
    await browser.close()
  File "D:\venv\pyppeteer2_demo\lib\site-packages\pyppeteer\browser.py", line 275, in close
    await self._closeCallback()
  File "D:\venv\pyppeteer2_demo\lib\site-packages\pyppeteer\launcher.py", line 128, in close
    return await self._close_proc()
  File "D:\venv\pyppeteer2_demo\lib\site-packages\pyppeteer\launcher.py", line 103, in _close_proc
    await self.connection.send('Browser.close')
pyppeteer.errors.NetworkError: Protocol error Browser.close: Target closed.

Process finished with exit code 1

```

**Comment by Mattwmaster58** [comment]
Ok, looks like this is a bug. We automatically code the browser on process end, so closing it manually causes the second choosing command to fail with that error. You can probably kinda safely ignore this error for now.

On the surface it seems that all that needs to be done is to make our atexit call back more fault tolerant.

**Comment by alternativshik** [comment]
Have the same issue, But I don't close browser, make some requests and get this exception

**Comment by Mattwmaster58** [comment]
@alternativshik It's likely you are encountering a separate issue. `pyppeteer.errors.NetworkError: Protocol error Browser.close: Target closed.` is what happens almost _anything_ goes wrong.
