### ISSUE TITLE
browser.close() raises error message when `userDataDir` option is set

### ISSUE THREAD

**Issue by Shmakov** [pyppeteer/pyppeteer#123]
I'm using latest version of pyppeteer (0.2.2 from `dev` branch) on Windows 10.

Minimal code to reproduce the issue:

```python
import asyncio
from pyppeteer import launch

async def test():
    browser = await launch({'userDataDir': 'test'})
    await browser.close()

asyncio.run(test())
```

And here is the error message:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\[ projects ]\kroger-cli\venv\lib\site-packages\pyppeteer\launcher.py", line 151, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "D:\Python\Python38\lib\asyncio\base_events.py", line 591, in run_until_complete
    self._check_closed()
  File "D:\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'Launcher.killChrome' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

Removing the `userDataDir` option from the launch eliminates the issue (i.e. everything is working as expected).

Is it something you can help with? Happy to provide any logs/details that could help. Thanks!

**Comment by Mattwmaster58** [comment]
The old cleanup code is really showing it's age at this point. My guess is that the coroutine never gets awaited because the profile dir cleanup fails because the process doesn't have the proper permissions to delete your data dir OR it's failing because it's trying to delete nothing (eg something like `self._profile_dir = None;...os.remove(self._profile_dir)`). Either way, I'm guessing it's failing to cleanup some directory, which causes further cleanup to fail.

The cleanup code has come a long way in `pup2.1.1`, but definitely still needs work.

**Comment by nahos** [comment]
I would like to work on this issue, this is my first time contributing to open source, so I might need some help. Would that be fine?

**Comment by Mattwmaster58** [comment]
@nahos that would be fine - like I said there have been significant improvements/changes on the `pup2.1.1` branch, so as a starting point if try to reproduce the issue there. I'd also recommend joining the matrix channel mentioned in #1

**Comment by Shmakov** [comment]
Thanks for looking into it @Mattwmaster58!

While trying to find a workaround for this I've found that using `asyncio.get_event_loop().run_until_complete()` doesn't produce the same exception. The exception is only raised while using `asyncio.run()`. I'm not completely familiar with asyncio, however their [documentation](https://docs.python.org/3/library/asyncio-eventloop.html) states that using `asyncio.run()` is generally a better idea.

And I presume you are right regarding the `profile dir cleanup fails`. Indeed `userDataDir` directory is not cleaned up, as it remains intact after the script finishes the execution.

**Comment by nahos** [comment]
@Mattwmaster58  I have  installed the pup2.1.1 version using the below command:
pip install -U git+https://github.com/pyppeteer/pyppeteer@pup2.1.1, please let me know if this is not right. With this installation, I am able to reproduce the issue.

**Comment by Mattwmaster58** [comment]
@nahos

> please let me know if this is not right

That would indeed be the correct command to use.
