### ISSUE TITLE
http.client.BadStatusLine:

### ISSUE THREAD

**Issue by WangDai1** [pyppeteer/pyppeteer#135]
raise BadStatusLine(line)
http.client.BadStatusLine: GET /json/version HTTP/1.1

**Comment by Mattwmaster58** [comment]
With no other context, this doesn't look like a bug with pyppeteer. Feel free to provide more info to inform me otherwise.

**Comment by YounusDev** [comment]
In my local environment works fine. But in centos 7 server does not.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/projects/amzwatch_system/scrapper.py", line 1424, in <module>
    Scrapper()
  File "/home/projects/amzwatch_system/scrapper.py", line 19, in __init__
    asyncio.get_event_loop().run_until_complete( self.__run_main() )  # init main actions
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/projects/amzwatch_system/scrapper.py", line 69, in __run_main
    await asyncio.gather(
  File "/home/projects/amzwatch_system/scrapper.py", line 87, in __handle_instances
    await asyncio.gather(
  File "/home/projects/amzwatch_system/scrapper.py", line 106, in __handle_browser_instances
    await asyncio.gather(
  File "/home/projects/amzwatch_system/scrapper.py", line 115, in __start_browser_instance
    temp_browser = await launch( headless=True )
  File "/usr/local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 305, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 166, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/usr/local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
    with urlopen(url) as f:
  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 1379, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.8/urllib/request.py", line 1354, in do_open
    r = h.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 285, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: GET /json/version HTTP/1.1

**Comment by YounusDev** [comment]
Now it's fixed. I have to run it in --no-sandbox mode in my server.

**Comment by Mattwmaster58** [comment]
Yep, in the future we are planning on having better error messages when something like this happens so you can actually see the error raised by the browser. In this case Chrome will emit a pretty specific message telling you exactly what's going wrong, but at this point in time that message unfortunately never propagates.

**Comment by ligou525** [comment]
> Yep, in the future we are planning on having better error messages when something like this happens so you can actually see the error raised by the browser. In this case Chrome will emit a pretty specific message telling you exactly what's going wrong, but at this point in time that message unfortunately never propagates.

Hi Matt,

Would you please help to see this case happed in requests-html when calling r.html.render(), thanks so much!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/work/.jumbo/lib/python3.6/site-packages/requests_html.py", line 586, in render
    self.browser = self.session.browser  # Automatically create a event loop and browser
  File "/home/work/.jumbo/lib/python3.6/site-packages/requests_html.py", line 730, in browser
    self._browser = self.loop.run_until_complete(super().browser)
  File "/home/work/.jumbo/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/work/.jumbo/lib/python3.6/site-packages/requests_html.py", line 714, in browser
    self._browser = await pyppeteer.launch(ignoreHTTPSErrors=not(self.verify), headless=True, args=self.__browser_args)
  File "/home/work/.jumbo/lib/python3.6/site-packages/pyppeteer/launcher.py", line 305, in launch
    return await Launcher(options, **kwargs).launch()
  File "/home/work/.jumbo/lib/python3.6/site-packages/pyppeteer/launcher.py", line 166, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/home/work/.jumbo/lib/python3.6/site-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
    with urlopen(url) as f:
  File "/home/work/.jumbo/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/work/.jumbo/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/home/work/.jumbo/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/home/work/.jumbo/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/work/.jumbo/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/work/.jumbo/lib/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/home/work/.jumbo/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/work/.jumbo/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/work/.jumbo/lib/python3.6/http/client.py", line 279, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: GET /json/version HTTP/1.1

**Comment by Mattwmaster58** [comment]
@ligou525 It's impossible to know without the output of the Chrome process on stdout/stderr, unfortunately. That's why I said in the future we'd like to better communicate what exactly is failing, but as of now that functionality is only a plan.

**Comment by shyandsy** [comment]
any solutions here？

**Comment by vishrutdixit** [comment]
I'm also getting this error with this very simple test code:
```
import asyncio
from pyppeteer import launch

async def main():
    browser = await launch()

asyncio.get_event_loop().run_until_complete(main())
```
```
  File "/usr/lib/python3.6/urllib/request.py", line 1328, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 289, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: GET /json/version HTTP/1.1
```

pyppeteer: v0.2.2
OS: Ubuntu 18.04.4 LTS
Python: v3.6.9

Note: I'm using WSL1 to run Ubuntu on Windows

**Comment by Shouheng88** [comment]
Hey guys, I have just found one solution for myself and I hope it can also help you. 

**I found that if you set the window size by `--window-size`, the headless parameter will be invalid. So if you want to use it in headless mode, do not add this argument.**

**Comment by kbreit** [comment]
I'm getting this error even though I am specifying `--no-sandbox`.

**Comment by mk-ship-it** [comment]
I think I figured this one out after stumbling into it myself. The traceback from @ligou525 includes a reference to this function `get_ws_endpoint` which turns out to be rather botched. `urllib.error.URLError` and `http.client.HTTPError`, base class of `BadStatusLine` aren't ancestors of each other, albeit `urllib` incorporates http.client to function.

Therefore I added the `HTTPError` to the caught exceptions in the "hot-patch" approach I noticed had been used by `pyppdf` for the `chromium_downloader.download_zip` function which now requires an ssl connection:

```
from http.client import HTTPException
from pyppeteer.errors import BrowserError
import pyppeteer.launcher
import time
from urllib.error import URLError
from urllib.request import urlopen

def get_ws_endpoint(url) -> str:
    url = url + '/json/version'
    timeout = time.time() + 30
    while True:
        if time.time() > timeout:
            raise BrowserError('Browser closed unexpectedly:\n')
        try:
            with urlopen(url) as f:
                data = json.loads(f.read().decode())
            break
        except (URLError, HTTPException) as e:
            pass
        time.sleep(0.1)

    return data['webSocketDebuggerUrl']


pyppeteer.launcher.get_ws_endpoint = get_ws_endpoint
```

As an additional plus, I'll also mention that the code never slept because it would always either `break` or `continue`. This part of the problem was caught by my IDE.

**Comment by champion-yang** [comment]
> Now it's fixed. I have to run it in --no-sandbox mode in my server.

gays, I add --no-sandbox in launch func, but I still receive `pyppeteer.errors.BrowserError: Browser closed unexpectedly:`, and you?

**Comment by champion-yang** [comment]
> I'm getting this error even though I am specifying `--no-sandbox`.

After specifying `--no-sandbox`, I reciived a new error, `pyppeteer.errors.BrowserError: Browser closed unexpectedly:`, and it maybe cause by `http.client.BadStatusLine: GET /json/version HTTP/1.1`

**Comment by Kronopt** [comment]
Hi guys.
I'm having the same problem.

Bare in mind that this runs OK on my local machine (windows 10), but when I run it on a linux container (heroku, in this case) it breaks.

```
Traceback (most recent call last):
  File "/app/test.py", line 32, in test
    self.browser = await launch()
  File "/app/.heroku/python/lib/python3.9/site-packages/pyppeteer/launcher.py", line 305, in launch
    return await Launcher(options, **kwargs).launch()
  File "/app/.heroku/python/lib/python3.9/site-packages/pyppeteer/launcher.py", line 166, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/app/.heroku/python/lib/python3.9/site-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
    with urlopen(url) as f:
  File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 1371, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 1346, in do_open
    r = h.getresponse()
  File "/app/.heroku/python/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/app/.heroku/python/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/app/.heroku/python/lib/python3.9/http/client.py", line 289, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: GET /json/version HTTP/1.1
```

I also tried with the `--no-sandbox` flag, but I get a different error, as has already been mention on this discussion before:

```
Traceback (most recent call last):
  File "/app/test", line 32, in test
    self.browser = await launch(options={"args": ['--no-sandbox']})
  File "/app/.heroku/python/lib/python3.9/site-packages/pyppeteer/launcher.py", line 305, in launch
    return await Launcher(options, **kwargs).launch()
  File "/app/.heroku/python/lib/python3.9/site-packages/pyppeteer/launcher.py", line 166, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/app/.heroku/python/lib/python3.9/site-packages/pyppeteer/launcher.py", line 225, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly
```


pyppeteer: v0.2.2
Python: v3.9.0
OS: Linux-4.4.0 (running on heroku, so I'm not sure)

**Comment by Kronopt** [comment]
I tried @mk-ship-it [solution](https://github.com/pyppeteer/pyppeteer/issues/135#issuecomment-728930052) but I get the same `pyppeteer.errors.BrowserError('Browser closed unexpectedly')`.

**Comment by Kronopt** [comment]
I explain my solution [here](https://github.com/pyppeteer/pyppeteer/issues/194#issuecomment-739012427).
Thanks to https://github.com/pyppeteer/pyppeteer/issues/108#issuecomment-642034439!

**Comment by aahnik** [comment]
If anybody is running on **Heroku** and facing the same error:

Add the **buildpack** : The url for the buildpack is below :

`https://github.com/jontewks/puppeteer-heroku-buildpack`

Ensure that you're using **`--no-sandbox`** mode

```python
launch({ args: ['--no-sandbox'] })
```

**Comment by lihuaxiaoyang** [comment]
I also run it in --no-sandbox mode in my server, but is not work

`Traceback (most recent call last):
File "test.py", line 20, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "test.py", line 7, in main
    browser = await launch(headless=True,opetions={'args':['--no-sandbox']})
  File "/home/lihua_xy/.local/lib/python3.7/site-packages/pyppeteer/launcher.py", line 305, in launch
    return await Launcher(options, **kwargs).launch()
  File "/home/lihua_xy/.local/lib/python3.7/site-packages/pyppeteer/launcher.py", line 166, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/home/lihua_xy/.local/lib/python3.7/site-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
    with urlopen(url) as f:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1378, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1353, in do_open
    r = h.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 292, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: GET /json/version HTTP/1.1
`
pyppeteer 0.2.2
CentOS 7.9
chromium 588429
Python 3.7.9

**Comment by zzx13971573117** [comment]
The problem I encountered is that I can run normally on windows and report an error when I use shell tools to run on Linux virtual machine.    http.client.BadStatusLine: GET /json/version HTTP/1.1

**Comment by vee-varun** [comment]
I was also facing the same issue. 
Tried after installing these yum packages and it worked.

- gtk3.x86_64
- libXScrnSaver
- alsa-lib.x86_64

**Comment by raymondguo-db** [comment]
I ran into this issue as well, and trying @mk-ship-it's [solution](https://github.com/pyppeteer/pyppeteer/issues/135#issuecomment-728930052) worked for me. Since it seems to be a solution that has worked for multiple folks, I opened up a PR that incorporates the solution: #293
