### ISSUE TITLE
Downloading a file (into memory) with pyppeteer

### ISSUE THREAD

**Issue by jessrosenfield** [pyppeteer/pyppeteer#136]
I'm navigating a site in pyppeteer that contains logic in which file download links must be followed in the same session in which they're surfaced. It's complex enough such that simply replaying the requests with postman fails and is not worth reverse-engineering. This means that I need to use pyppeteer to follow a direct link to download a file.

I've looked at these links for how this is done in puppeteer:
https://stackoverflow.com/questions/46966341/puppeteer-how-to-set-download-location
https://stackoverflow.com/questions/55408302/how-to-get-the-download-stream-buffer-using-puppeteer

and I'm a bit confused because
a) it appears that [setDownloadBehavior](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-setDownloadBehavior) is deprecated
b) if I were to use `page.evaluate` to use puppeteer-type logic, I'm not sure how I would send data back into my python script. Ideally I would read the file into memory to upload to s3 and skip writing to disk.

**Comment by Mattwmaster58** [comment]
Hmm, the second SO link seems to give a pretty good solution. I'm not familiar with state of request interception on the last release, though.

**Comment by jessrosenfield** [comment]
I get the following error on 0.2.2:
```
Task exception was never retrieved
 exception=NetworkError('Protocol error (Network.getResponseBody): No resource with given identifier found')>
Traceback (most recent call last):
  File "index.py", line 104, in handle_response
    buffer = await response.buffer()
  File "pyppeteer/network_manager.py", line 654, in _bufread
    'requestId': self._request._requestId
pyppeteer.errors.NetworkError: Protocol error (Network.getResponseBody): No resource with given identifier found
```
here is my implementation:
```
async def get_doc_from_link(self, link):
        # adadpted from https://stackoverflow.com/questions/55408302/how-to-get-the-download-stream-buffer-using-puppeteer
        page = await self.browser.newPage()
        initial_request = True
        buffer = None
        await page.setRequestInterception(True)
        async def handle_request(request):
            if request.isNavigationRequest() and not initial_request:
                await request.abort()
            else:
                initialRequest = False
                await request.continue_()
        async def handle_response(response):
            buffer = await response.buffer()
            # DEBUG: DELETEME
            with open('test.doc', 'wb') as outfile:
                outfile.write(buffer)
        page.on('request', lambda request: asyncio.ensure_future(handle_request(request)))
        page.on('response', lambda response: asyncio.ensure_future(handle_response(response)))
        await page.goto(link)
        await page.close()
        return buffer
```

**Comment by jessrosenfield** [comment]
I also get an error when I try to download to disk:
Error:
```
Traceback (most recent call last):
  File "<REDACTED>/twisted/internet/defer.py", line 824, in adapt
    extracted = result.result()
  File "index.py", line 80, in load_index
    await self.get_doc_from_temp_download(search_download_link)
  File "index.py", line 99, in get_doc_from_temp_download
    await page.goto(link, {'waitUntil': 'networkidle0'})
  File "<REDACTED>", line 879, in goto
    raise PageError(result)
pyppeteer.errors.PageError: net::ERR_ABORTED at <REDACTED>
```
Implementation:
```
async def get_doc_from_temp_download(self, link):
        page = await self.browser.newPage()
        with tempfile.TemporaryDirectory() as tmpdirname:
            await page._client.send('Page.setDownloadBehavior', {
                'behavior': 'allow',
                'downloadPath': tmpdirname,
            })
            await page.goto(link, {'waitUntil': 'networkidle0'})
            print('supposedly done with download')
            print(tmpdirname, os.listdir(tmpdirname))
            import shutil; shutil.copytree(tmpdirname, 'test')
            await page.close()
```

**Comment by Mattwmaster58** [comment]
Well, now I'm slightly more familiar with the state of request interception in the last release, and it looks like it's pretty broken. Good news though, I can confirmed that it has already received a much needed upgrade in the `pup2.1.1` branch.

**Comment by standag** [comment]
I solved it by this function:
```python
async def get_pdf(self, url: str) -> bytes:
    response = await self._page.evaluate(
        f"""
        async () => {{
            function sleep(ms) {{
                return new Promise(resolve => setTimeout(resolve, ms));
                }};
            reader = new FileReader();
            response = await window.fetch("{url}")
            reader = new FileReader();
            data = await response.blob();
            buffer = await data.arrayBuffer();
            reader.readAsDataURL(data);
            for (i = 0; i < 60; i++) {{
                if (reader.readyState == 2){{break;}}
                console.log("loop " + i)
                await sleep(500)
                }}
            return reader.result
        }}"""
    )
    return base64.b64decode(response.encode().split(b",")[1])
```
