### ISSUE TITLE
How to use with Windows Subsystem for Linux (wsl) version 1?

### ISSUE THREAD

**Issue by NotoriousRebel** [pyppeteer/pyppeteer#142]
When I install the package on wslv1 and attempt to take a screenshot I get this error.
When I install it on Windows 10 it works just fine.
This is the traceback
``` % python3 screenshot.py
/usr/local/lib/python3.7/dist-packages/trio/_core/_multierror.py:472: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full 
Original exception was:
Traceback (most recent call last):
  File "screenshot.py", line 2, in <module>
    from pyppeteer import launch
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/__init__.py", line 30, in <module>
    from pyppeteer.launcher import connect, launch, executablePath  # noqa: E402
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/launcher.py", line 25, in <module>
    from pyppeteer.browser import Browser
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/browser.py", line 11, in <module>
    from pyee import EventEmitter
  File "/usr/local/lib/python3.7/dist-packages/pyee/__init__.py", line 59, in <module>
    from pyee._trio import TrioEventEmitter  # noqa
  File "/usr/local/lib/python3.7/dist-packages/pyee/_trio.py", line 4, in <module>
    import trio
  File "/usr/local/lib/python3.7/dist-packages/trio/__init__.py", line 18, in <module>
    from ._core import (
  File "/usr/local/lib/python3.7/dist-packages/trio/_core/__init__.py", line 19, in <module>
    from ._run import (
  File "/usr/local/lib/python3.7/dist-packages/trio/_core/_run.py", line 22, in <module>
    from outcome import Error, Value, capture
  File "/usr/local/lib/python3.7/dist-packages/outcome/__init__.py", line 11, in <module>
    from ._async import Error, Outcome, Value, acapture, capture
  File "/usr/local/lib/python3.7/dist-packages/outcome/_async.py", line 3, in <module>
    from ._sync import Error as ErrorBase
  File "/usr/local/lib/python3.7/dist-packages/outcome/_sync.py", line 28, in <module>
    class Outcome(ABC):
  File "/usr/local/lib/python3.7/dist-packages/outcome/_sync.py", line 43, in Outcome
    _unwrapped = attr.ib(default=False, eq=False, init=False)
TypeError: attrib() got an unexpected keyword argument 'eq
```

The code was just the python screenshot example.

```python
import asyncio
from pyppeteer import launch

async def main():
    browser = await launch()
    page = await browser.newPage()
    await page.goto('https://example.com')
    await page.screenshot({'path': 'example.png'})
    await browser.close()

asyncio.get_event_loop().run_until_complete(main())
```

**Comment by Mattwmaster58** [comment]
Aside from making sure all dependancies are up to date, I'm not sure that this is a `pyppeteer` issue.

**Comment by NotoriousRebel** [comment]
Thanks for the quick reply! Is there an easy to verify that? I tried with both the dev version and normal version? When I run the code it doesn't even attempt to download chromium?

**Comment by Mattwmaster58** [comment]
The traceback shows that the exception is raised while trying to import Trio

**Comment by NotoriousRebel** [comment]
Might be related to [this issue](https://github.com/python-trio/trio/issues/893).
Regardless, I would bet when I upgrade to WSLv2 the error magically disappears
