### ISSUE TITLE
How to properly cleanup non-existent chromium processes?

### ISSUE THREAD

**Issue by NotoriousRebel** [pyppeteer/pyppeteer#144]
OS Info: Windows 10 v1909
Python version: Python 3.7.0
Pyppeteer version: pyppeteer==0.2.2 (also tried with dev version and ran into same problem)

I am trying to take screenshots for 14 websites and of those 14 screenshots, 13 are successful. Which is great! However, one fails with 
Exception occurred: net::ERR_SSL_PROTOCOL_ERROR which is just because of me using https when it only supports http.
However, the bigger problem is processes aren't getting cleaned up:
![image](https://user-images.githubusercontent.com/36310667/86081349-272cd680-ba63-11ea-8bc3-d9596411b1ff.png)

Here is a snippet of the code with the screenshot functionality
```python
    async def take_screenshot(self, url):
        url = f'http://{url}' if ('http' not in url and 'https' not in url) else url
        # url = f'https://{url}' if ('http' not in url and 'https' not in url) else url
        url = url.replace('www.', '')
        print(f'Taking a screenshot of: {url}')
        browser = await launch(headless=True, ignoreHTTPSErrors=True, args=["--no-sandbox"])
        browser = await browser.createIncognitoBrowserContext()
        page = await browser.newPage()
        try:

            # change default timeout from 30 to 35 seconds
            page.setDefaultNavigationTimeout(35000)
            await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) '
                                    'Chrome/83.0.4103.106 Safari/537.36')
            await page.goto(url, waitUntil='networkidle0')
            await page.screenshot({'path': f'{self.output}\\{url.replace("http://", "").replace("https://", "")}.png'})
            print('inside try and page has been closed')
            await page.close()
            # await browser.close()
            # return True
        except Exception as e:
            print(f'Exception occurred: {e} for: {url} ')
        # No matter what happens make sure browser and page are closed
        if page.isClosed() is False:
            print('page is closed as false')
            await page.close()
        print('browser is closed')
        await browser.close()
```

This is output from screenshot function when run:

```
Taking a screenshot of: https://x
Taking a screenshot of: https://x
Taking a screenshot of: https://x
Taking a screenshot of: https://x
Taking a screenshot of: https://x
Taking a screenshot of: https://x
Taking a screenshot of: https://x
Taking a screenshot of: https://x
Taking a screenshot of: https://x
Taking a screenshot of: https://x
inside try and page has been closed
browser is closed
Taking a screenshot of: https://x
Taking a screenshot of: https://x
Taking a screenshot of: https://x
Taking a screenshot of: https://x
Exception occurred: net::ERR_SSL_PROTOCOL_ERROR at https://x for: https://x
page is closed as false
browser is closed
inside try and page has been closed
browser is closed
inside try and page has been closed
browser is closed
inside try and page has been closed
browser is closed
inside try and page has been closed
browser is closed
inside try and page has been closed
browser is closed
inside try and page has been closed
browser is closed
inside try and page has been closed
browser is closed
inside try and page has been closed
browser is closed
inside try and page has been closed
browser is closed
inside try and page has been closed
browser is closed
inside try and page has been closed
browser is closed
inside try and page has been closed
browser is closed
```

**Comment by NotoriousRebel** [comment]
Furthermore, for some urls
for example: "http://ispspeedindex.netflix.com" 
with a timeout of 35 seconds it exceeds the timeout and causes a chromium process to just hang:
![image](https://user-images.githubusercontent.com/36310667/86518778-f69dc180-be01-11ea-88ac-4ba17d50d3d4.png)
If you manually kill the process you will see it seems to get caught in an infinite loop:
```Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
An exception has occurred while mapping: Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\aiomultiprocess\pool.py", line 79, in run
    result = future.result()
  File "C:\screenshotcode\screenshot.py", line 75, in take_screenshot
    await page.close()
  File "C:\Python37\lib\site-packages\pyppeteer\page.py", line 1504, in close
    {'targetId': self._target._targetId})
pyppeteer.errors.NetworkError: Protocol error Target.closeTarget: Target closed.
```

**Comment by kiwi0fruit** [comment]
may be relevant:

* https://github.com/miyakogi/pyppeteer/issues/274
* https://github.com/kiwi0fruit/pyppdf/issues/9

**Comment by reuning** [comment]
I'm curious if anyone has found any sort of solution to this?

**Comment by kiwi0fruit** [comment]
I tried to fix it in the latest version of the pyppdf. But I didn't reproduce the bug hence I don't know if it works.

**Comment by Mattwmaster58** [comment]
This seems to be a recurring issue unfortunately. It's annoying to have a tiered approach of gracefully asking chrome to die, then killing it forcefully (or at least I'm pretty sure that's how it works in the pup2.1.1 branch). We may have to go for a more robust, reliable solution.

**Comment by colinsarah** [comment]
how to fix zombie process in docker？appreciate any

**Comment by colinsarah** [comment]
just use dumb-init

**Comment by yfeic** [comment]
I use a new close method to close browser.

 ```
   async def _close_browser(self)->None:
        process_browser=self.browser.process
        if process_browser and process_browser.pid:
            process_browser.kill()
            process_browser.wait()
        pass
```
