### ISSUE TITLE
http.client.BadStatusLine ERROR (ver 0.2.2)

### ISSUE THREAD

**Issue by NorthPhantom** [pyppeteer/pyppeteer#147]
I have got an error in 0.2.2 and anything is ok when I use 0.0.25.

Even I used the same URL, there also were errors sometimes. I tried py3.6 3.7 3.8, the error is still there.

The error like that:

```
Traceback (most recent call last):
  File "51_get_info_pyppeteer.py", line 187, in <module>
    asyncio.get_event_loop().run_until_complete(url_task())
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "51_get_info_pyppeteer.py", line 120, in url_task
    san_title_ret = await get_url_title_wrapper(san)
  File "51_get_info_pyppeteer.py", line 102, in get_url_title_wrapper
    title_http, log_http = await get_url_title_pyppeteer("http://" + url, url + "_http")
  File "51_get_info_pyppeteer.py", line 55, in get_url_title_pyppeteer
    'dumpio': False,
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/launcher.py", line 305, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/launcher.py", line 166, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
    with urlopen(url) as f:
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 279, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: GET /json/version HTTP/1.1

```

**Comment by Mattwmaster58** [comment]
See #135
