### ISSUE TITLE
Page freezes when webpage contains JS exception

### ISSUE THREAD

**Issue by csreddy** [pyppeteer/pyppeteer#167]
Initially I encountered page hanging after navigating a handful of links. Fixed the issue by setting `dumpio=True` as suggested in https://github.com/miyakogi/pyppeteer/issues/167. However now the page completely hangs if webpage contains JS exception and times out with `InvalidStateError`

URL trying to access: http://www4.law.cornell.edu/uscode/42/3604.html

JS exception: 
```
Uncaught TypeError: Cannot read property 'getElementsByClassName' of null
    at HTMLDocument.<anonymous> (lii_scriptinator.min.js:1)
    at l (jquery-3.3.1.min.js:2)
    at c (jquery-3.3.1.min.js:2)
```

### Pyppeteer exception

```
[0828/164428.989667:WARNING:cors_url_loader_factory.cc(212)] |cors_exempt_headers| contains unexpected key: Purpose
[0828/164428.989994:WARNING:cors_url_loader_factory.cc(212)] |cors_exempt_headers| contains unexpected key: Purpose
[0828/164429.169955:INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'getElementsByTagName' of undefined", source: https://www.law.cornell.edu/staticsite_scripts/lii_scriptinator.min.js (1)
[0828/164429.333329:INFO:CONSOLE(1)] "set lii_fundraiser disabled", source: https://www.law.cornell.edu/staticsite_scripts/lii_scriptinator.min.js (1)
[0828/164429.333329:INFO:CONSOLE(1)] "set lii_fundraiser disabled", source: https://www.law.cornell.edu/staticsite_scripts/lii_scriptinator.min.js (1)
 Failed to load url: http://www4.law.cornell.edu/uscode/42/3604.html. Navigation Timeout Exceeded: 30000 ms exceeded.
[E:pyppeteer.connection] connection unexpectedly closed
Task exception was never retrieved
future: <Task finished coro=<Connection._async_send() done, defined at /opt/python/pyppeteer/connection.py:69> exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
File "/opt/python/websockets/protocol.py", line 827, in transfer_data
message = await self.read_message()
File "/opt/python/websockets/protocol.py", line 895, in read_message
frame = await self.read_data_frame(max_size=self.max_size)
File "/opt/python/websockets/protocol.py", line 971, in read_data_frame
frame = await self.read_frame(max_size)
File "/opt/python/websockets/protocol.py", line 1051, in read_frame
extensions=self.extensions,
File "/opt/python/websockets/framing.py", line 105, in read
data = await reader(2)
File "/var/lang/lib/python3.7/asyncio/streams.py", line 677, in readexactly
raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/opt/python/pyppeteer/connection.py", line 73, in _async_send
await self.connection.send(msg)
File "/opt/python/websockets/protocol.py", line 555, in send
await self.ensure_open()
File "/opt/python/websockets/protocol.py", line 803, in ensure_open
raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/python/pyppeteer/connection.py", line 79, in _async_send
await self.dispose()
File "/opt/python/pyppeteer/connection.py", line 170, in dispose
await self._on_close()
File "/opt/python/pyppeteer/connection.py", line 153, in _on_close
f'Protocol error {cb.method}: Target closed.', # type: ignore
asyncio.base_futures.InvalidStateError: invalid state
```

**Comment by csreddy** [comment]
Apologize for the false alarm. This is was due to user error. I had setup event handlers for page events `pageerror`. Handler function is supposed to be async. Changing so fixed the hang issue.
