### ISSUE TITLE
Chromium 722234 not running on Mac Catalina 10.15.6

### ISSUE THREAD

**Issue by jtf9808** [pyppeteer/pyppeteer#171]
Hi,
I'm trying to use the pup2.2.1 branch however the default version of chromium refuses to launch on my mac (running Catalina 10.15.6) even when I try to launch it manually. I had the same issue on a much older (2010) macbook as well. Is there anyway around this/ any other version of chromium that is compatible?

**Comment by csreddy** [comment]
You may want to post error stack trace in order for folks to provide any meaningful response to your issue..

**Comment by jtf9808** [comment]
Apologies for the delay this is the traceback I get

Traceback (most recent call last):
  File "/Users/jackfulls/Python_stuff/Scrapy/lib/python3.8/site-packages/scrapy/crawler.py", line 192, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "/Users/jackfulls/Python_stuff/Scrapy/lib/python3.8/site-packages/scrapy/crawler.py", line 196, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/Users/jackfulls/Python_stuff/Scrapy/lib/python3.8/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/Users/jackfulls/Python_stuff/Scrapy/lib/python3.8/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/Users/jackfulls/Python_stuff/Scrapy/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/Users/jackfulls/Python_stuff/Scrapy/lib/python3.8/site-packages/scrapy/crawler.py", line 87, in crawl
    self.engine = self._create_engine()
  File "/Users/jackfulls/Python_stuff/Scrapy/lib/python3.8/site-packages/scrapy/crawler.py", line 101, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/Users/jackfulls/Python_stuff/Scrapy/lib/python3.8/site-packages/scrapy/core/engine.py", line 69, in __init__
    self.downloader = downloader_cls(crawler)
  File "/Users/jackfulls/Python_stuff/Scrapy/lib/python3.8/site-packages/scrapy/core/downloader/__init__.py", line 83, in __init__
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "/Users/jackfulls/Python_stuff/Scrapy/lib/python3.8/site-packages/scrapy/middleware.py", line 53, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/Users/jackfulls/Python_stuff/Scrapy/lib/python3.8/site-packages/scrapy/middleware.py", line 35, in from_settings
    mw = create_instance(mwcls, settings, crawler)
  File "/Users/jackfulls/Python_stuff/Scrapy/lib/python3.8/site-packages/scrapy/utils/misc.py", line 156, in create_instance
    instance = objcls.from_crawler(crawler, *args, **kwargs)
  File "/Users/jackfulls/Python_stuff/Scrapy/scrapeme/CoLP_test/CoLP_test/middlewares.py", line 101, in from_crawler
    o = loop.run_until_complete(cls._from_crawler(crawler))
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/jackfulls/Python_stuff/Scrapy/scrapeme/CoLP_test/CoLP_test/middlewares.py", line 112, in _from_crawler
    o.browser = await launch(handleSIGTERM=False, handleSIGINT=False, devtools=False,
  File "/Users/jackfulls/Python_stuff/Scrapy/lib/python3.8/site-packages/pyppeteer/__init__.py", line 100, in launch
    return await Pyppeteer(projectRoot, preferredRevision).launch(**kwargs)
  File "/Users/jackfulls/Python_stuff/Scrapy/lib/python3.8/site-packages/pyppeteer/__init__.py", line 52, in launch
    return await self._launcher.launch(**kwargs)
  File "/Users/jackfulls/Python_stuff/Scrapy/lib/python3.8/site-packages/pyppeteer/launcher.py", line 316, in launch
    raise original_exception
  File "/Users/jackfulls/Python_stuff/Scrapy/lib/python3.8/site-packages/pyppeteer/launcher.py", line 302, in launch
    browser = await Browser.create(
  File "/Users/jackfulls/Python_stuff/Scrapy/lib/python3.8/site-packages/pyppeteer/browser.py", line 135, in create
    await connection.send('Target.setDiscoverTargets', {'discover': True})
pyppeteer.errors.NetworkError: Protocol error Target.setDiscoverTargets: Target closed.

**Comment by Granitosaurus** [comment]
What version of chrome are your running? Try with the latest version by exporting env variable first:

```
$PYPPETEER_CHROMIUM_REVISION = $(curl https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/
Linux_x64%2FLAST_CHANGE?alt=media)
```
You can also try `pup2.1.1` branch

**Comment by jtf9808** [comment]
So I was trying to run the `pup2.1.1` branch (not the 2.2.1 branch like I incorrectly said before) and trying to use the default version of chromium that downloads from that package. Just tried using the latest version of chromium and it worked!
