### ISSUE TITLE
Websockets client breaks

### ISSUE THREAD

**Issue by gulfpearl** [pyppeteer/pyppeteer#203]
When I crawl through more than about 500 pages, in any order, the websockets breaks, here is the traceback:

[E:pyppeteer.connection] connection unexpectedly closed
Task exception was never retrieved
future: <Task finished name='Task-30222' coro=<Connection._async_send() done, defined at /home/mike/projects/env/lib/python3.9/site-packages/pyppeteer/connection.py:69> exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
  File "/home/mike/projects/env/lib/python3.9/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/mike/projects/env/lib/python3.9/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/mike/projects/env/lib/python3.9/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/mike/projects/env/lib/python3.9/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/mike/projects/env/lib/python3.9/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.9/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mike/projects/env/lib/python3.9/site-packages/pyppeteer/connection.py", line 73, in _async_send
    await self.connection.send(msg)
  File "/home/mike/projects/env/lib/python3.9/site-packages/websockets/protocol.py", line 555, in send
    await self.ensure_open()
  File "/home/mike/projects/env/lib/python3.9/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mike/projects/env/lib/python3.9/site-packages/pyppeteer/connection.py", line 79, in _async_send
    await self.dispose()
  File "/home/mike/projects/env/lib/python3.9/site-packages/pyppeteer/connection.py", line 170, in dispose
    await self._on_close()
  File "/home/mike/projects/env/lib/python3.9/site-packages/pyppeteer/connection.py", line 151, in _on_close
    cb.set_exception(_rewriteError(
asyncio.exceptions.InvalidStateError: invalid state

**Comment by Mattwmaster58** [comment]
Could you provide the code necessary to reproduce this issue?

**Comment by max36067** [comment]
I have same problem, too!
Here is my code.
`
class Downloader:
    def __init__(self, log, browser):
        self.log = log
        self.browser = browser

    async def fetch(self, request):
        url = request.url
        headers = request.headers
        page = await self.browser.newPage()
        await page.setJavaScriptEnabled(True)
        try:
            await page.setExtraHTTPHeaders(headers)
            resp = await page.goto(url)
            status_code = resp.status
            html = await resp.text()
            response = Response(request, status=status_code, html=html)
        except Exception as e:
            response = Response(request, status="error", error=str(e))
        finally:
            await asyncio.sleep(1)
            await page.close()
            return response
`

My browser create ouside the function, and it look like this.
`
browser = await launch(
                handleSIGINT=False,
                handleSIGTERM=False,
                handleSIGHUP=False,
                headless=True,
                args=[
                    '--no-sandbox',
                    '--disable-setuid-sandbox',
                    '--single-process',
                    '--disable-dev-shm-usage',
                    '--disable-gpu',
                    '--no-zygote'
                ]
            )
`
It works on my local mac, but not on cloud k8s.
Thank you!
