### ISSUE TITLE
http.client.RemoteDisconnected: Remote end closed connection without response

### ISSUE THREAD

**Issue by towry** [pyppeteer/pyppeteer#211]
error message:

```txt
HTTPServerRequest(protocol='http', host='localhost:9010', method='POST', uri='/api/publish', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/towry/Library/Caches/pypoetry/virtualenvs/xx-xxxx-service-5jmTp2X7-py3.8/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/Users/towry/Projects/project_xxxxx/project_xxxxx/handler/xyxyxy.py", line 22, in post
        browser = await get_browser()
      File "/Users/towry/Projects/project_xxxxx/project_xxxxx/browser_instance.py", line 24, in get_browser
        browser = await get_pp_browser(options = {
      File "/Users/towry/Projects/project_xxxxx/project_xxxxx/vendor/zp_publish_worker/browser_instance.py", line 56, in get_pp_browser
        browser = await pyppeteer.launcher.launch(default_opts)
      File "/Users/towry/Library/Caches/pypoetry/virtualenvs/xx-xxxx-service-5jmTp2X7-py3.8/lib/python3.8/site-packages/pyppeteer/launcher.py", line 306, in launch
        return await Launcher(options, **kwargs).launch()
      File "/Users/towry/Library/Caches/pypoetry/virtualenvs/xx-xxxx-service-5jmTp2X7-py3.8/lib/python3.8/site-packages/pyppeteer/launcher.py", line 167, in launch
        self.browserWSEndpoint = get_ws_endpoint(self.url)
      File "/Users/towry/Library/Caches/pypoetry/virtualenvs/xx-xxxx-service-5jmTp2X7-py3.8/lib/python3.8/site-packages/pyppeteer/launcher.py", line 228, in get_ws_endpoint
        with urlopen(url) as f:
      File "/Users/towry/.pyenv/versions/3.8.7/lib/python3.8/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/Users/towry/.pyenv/versions/3.8.7/lib/python3.8/urllib/request.py", line 525, in open
        response = self._open(req, data)
      File "/Users/towry/.pyenv/versions/3.8.7/lib/python3.8/urllib/request.py", line 542, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
      File "/Users/towry/.pyenv/versions/3.8.7/lib/python3.8/urllib/request.py", line 502, in _call_chain
        result = func(*args)
      File "/Users/towry/.pyenv/versions/3.8.7/lib/python3.8/urllib/request.py", line 1379, in http_open
        return self.do_open(http.client.HTTPConnection, req)
      File "/Users/towry/.pyenv/versions/3.8.7/lib/python3.8/urllib/request.py", line 1354, in do_open
        r = h.getresponse()
      File "/Users/towry/.pyenv/versions/3.8.7/lib/python3.8/http/client.py", line 1347, in getresponse
        response.begin()
      File "/Users/towry/.pyenv/versions/3.8.7/lib/python3.8/http/client.py", line 307, in begin
        version, status, reason = self._read_status()
      File "/Users/towry/.pyenv/versions/3.8.7/lib/python3.8/http/client.py", line 276, in _read_status
        raise RemoteDisconnected("Remote end closed connection without"
    http.client.RemoteDisconnected: Remote end closed connection without response
```

See https://github.com/pyppeteer/pyppeteer/blob/f89052763de15c029ab647b150856c3ea80f45dc/pyppeteer/launcher.py#L231

I have to add `http.client.RemoteDisconnected` exception to get it work.

**Comment by towry** [comment]
https://chromium.cypress.io/linux/stable/84.0.4147.89

**Comment by pathikrit-repo-personal** [comment]
@towry  can you describe this problem and if it is solved cause i am getting the same issue but only when a put it in a aws serverless layer

**Comment by towry** [comment]
@pathikrit-repo-personal I solved it by changing the Chrome to a specific version. Because latest Chrome works fine but the stealth plugin not work, older browser has this connection issue.

How I found the specific version that works? I try one by one on https://chromium.cypress.io
