### ISSUE TITLE
http.client.RemoteDisconnected: Remote end closed connection without response

### ISSUE THREAD

**Issue by ezerear** [pyppeteer/pyppeteer#223]
Hi, I tried to use pyppeter for the first time. It downloaded chromium normally, but the following problems occurred
```
import asyncio
from pyppeteer import launch

async def main():
    browser = await launch()
    page = await browser.newPage()
    await page.goto('https://example.com')
    await page.screenshot({'path': 'example.png'})
    await browser.close()

asyncio.get_event_loop().run_until_complete(main())
```

**error message output**

```
[W:pyppeteer.chromium_downloader] start chromium download.
Download may take a few minutes.
100%|██████████| 86759503/86759503 [00:21<00:00, 4078197.44it/s]
[W:pyppeteer.chromium_downloader] 
chromium download done.
[W:pyppeteer.chromium_downloader] chromium extracted to: /Users/apple/Library/Application Support/pyppeteer/local-chromium/588429
Traceback (most recent call last):
  File "/Users/apple/pythonProject/Screenshot/test.py", line 11, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/Users/apple/.pyenv/versions/3.6.8/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/Users/apple/pythonProject/Screenshot/test.py", line 5, in main
    browser = await launch()
  File "/Users/apple/.pyenv/versions/3.6.8/envs/celerytest/lib/python3.6/site-packages/pyppeteer/launcher.py", line 306, in launch
    return await Launcher(options, **kwargs).launch()
  File "/Users/apple/.pyenv/versions/3.6.8/envs/celerytest/lib/python3.6/site-packages/pyppeteer/launcher.py", line 167, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/Users/apple/.pyenv/versions/3.6.8/envs/celerytest/lib/python3.6/site-packages/pyppeteer/launcher.py", line 228, in get_ws_endpoint
    with urlopen(url) as f:
  File "/Users/apple/.pyenv/versions/3.6.8/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/apple/.pyenv/versions/3.6.8/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Users/apple/.pyenv/versions/3.6.8/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Users/apple/.pyenv/versions/3.6.8/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Users/apple/.pyenv/versions/3.6.8/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/Users/apple/.pyenv/versions/3.6.8/lib/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/Users/apple/.pyenv/versions/3.6.8/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/Users/apple/.pyenv/versions/3.6.8/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Users/apple/.pyenv/versions/3.6.8/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```
Any idea or workaround?

I am using the following version of pyppeteer:

```
$  pip list | grep pyppeteer
pyppeteer (0.0.25)
```

**Comment by CandyMi** [comment]
I have the same problem! Are there any good ideas?

**Comment by xieyiwen** [comment]
Me too, but wait a moment before connect to browser is fine.
Like this:
file : launcher.py Line166.

```
connectionDelay = self.slowMo
//sleep a moment
await asyncio.sleep(connectionDelay)
self.browserWSEndpoint = get_ws_endpoint(self.url)
```

use:
```
browser = await launch(headless=False, ignoreDefaultArgs=True, dumpio=True, handleSIGTERM=False,
                           handleSIGINT=False, args=args, logLevel=logging.DEBUG, ignoreHTTPSErrors=True,
                           autoClose=True, slowMo=10)
```

**Comment by ezerear** [comment]
Sorry, I saw your message so late. My problem has been solved. The problem
lies in clash x. My mac has opened this v2ray proxy, which caused pyppeteer
to fail to communicate to chromium. I closed clash x. Then everything is
normal. So please check if a similar proxy is turned on and then turn it
off!

xieyiwen ***@***.***> 于 2021年5月27日周四 下午7:37写道：
