### ISSUE TITLE
Cannot catch any errors whatsoever.

### ISSUE THREAD

**Issue by dracoDevs** [pyppeteer/pyppeteer#242]
I have a try catch that can catch any error using the following code:
```
try:
    <code_here>
except Exception as e:
    print('Unknown Error: ' + e)
```

But instead of just printing the following exception this is printed.

```
[E:pyppeteer.connection] connection unexpectedly closed
Task exception was never retrieved
future: <Task finished name='Task-738' coro=<Connection._async_send() done, defined at C:\users\draco\appdata\local\programs\python\python38\lib\site-packages\pyppeteer\connection.py:69> exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
  File "C:\users\draco\appdata\local\programs\python\python38\lib\site-packages\websockets\protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "C:\users\draco\appdata\local\programs\python\python38\lib\site-packages\websockets\protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "C:\users\draco\appdata\local\programs\python\python38\lib\site-packages\websockets\protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "C:\users\draco\appdata\local\programs\python\python38\lib\site-packages\websockets\protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "C:\users\draco\appdata\local\programs\python\python38\lib\site-packages\websockets\framing.py", line 105, in read
    data = await reader(2)
  File "C:\users\draco\appdata\local\programs\python\python38\lib\asyncio\streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\users\draco\appdata\local\programs\python\python38\lib\site-packages\pyppeteer\connection.py", line 73, in _async_send
    await self.connection.send(msg)
  File "C:\users\draco\appdata\local\programs\python\python38\lib\site-packages\websockets\protocol.py", line 555, in send
    await self.ensure_open()
  File "C:\users\draco\appdata\local\programs\python\python38\lib\site-packages\websockets\protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\users\draco\appdata\local\programs\python\python38\lib\site-packages\pyppeteer\connection.py", line 79, in _async_send
    await self.dispose()
  File "C:\users\draco\appdata\local\programs\python\python38\lib\site-packages\pyppeteer\connection.py", line 170, in dispose
    await self._on_close()
  File "C:\users\draco\appdata\local\programs\python\python38\lib\site-packages\pyppeteer\connection.py", line 151, in _on_close
    cb.set_exception(_rewriteError(
asyncio.exceptions.InvalidStateError: invalid state
```

**Comment by nonewind** [comment]
I hava some error...... how can i do?

**Comment by nonewind** [comment]
I have same err.... what can i do ?
