### ISSUE TITLE
[bug] nbconvert --to webpdf 

### ISSUE THREAD

**Issue by tweigel-dev** [pyppeteer/pyppeteer#247]
## Bugreport
I try to use nbconvert at a pipeline at gitlab using docker to extract the ipynb as **webpdf**.This fails. But exporting it as **html** is no problem.
docker image: python:3.8
I run this command:
```
jupyter nbconvert --to webpdf --allow-chromium-download Untitled.ipynb
```

after downloading chromium it crashes after a few seconds with this output:
```
chromium download done.
[W:pyppeteer.chromium_downloader] chromium extracted to: /root/.local/share/pyppeteer/local-chromium/588429
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/usr/local/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/usr/local/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/usr/local/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/usr/local/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/local/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/local/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/local/lib/python3.8/site-packages/nbconvert/exporters/webpdf.py", line 93, in from_notebook_node
    pdf_data = self.run_pyppeteer(html)
  File "/usr/local/lib/python3.8/site-packages/nbconvert/exporters/webpdf.py", line 83, in run_pyppeteer
    pdf_data = pool.submit(run_coroutine, main()).result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/nbconvert/exporters/webpdf.py", line 82, in run_coroutine
    return loop.run_until_complete(coro)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/nbconvert/exporters/webpdf.py", line 42, in main
    browser = await self._check_launch_reqs()(
  File "/usr/local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 306, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 167, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/usr/local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 226, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:
```
Thanks for your help!

**Comment by shreve** [comment]
Disabling the chromium sandbox fixed this in several environments for me. It is still broken in a 3rd party environment, but it works in my kubernetes cluster and locally in docker.

```
c.WebPDFExporter.disable_sandbox = True
# or 
jupyter nbconvert --to webpdf --WebPDFExporter.disable_sandbox=True Untitled.ipynb
```

**Comment by jawiv** [comment]
thanks @shreve. This solved an issue for me where nbconvert would never progress past "Building PDF"

**Comment by SrinivasanShanmugam1311** [comment]
Dear Friends,

I am seeing this, while using nbconvert to pdf, any inputs or pointers onto this please, would be highly appreciated

C:\Users\user\anaconda3\Scripts>jupyter.exe nbconvert --to webpdf --WebPDFExporter.disable_sandbox=True C:\Users\user\Downloads\MDP_introduction.ipynb
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\anaconda3\Scripts\jupyter-nbconvert.EXE\__main__.py", line 4, in <module>
  File "C:\Users\user\anaconda3\Lib\site-packages\nbconvert\nbconvertapp.py", line 193, in <module>
    class NbConvertApp(JupyterApp):
  File "C:\Users\user\anaconda3\Lib\site-packages\nbconvert\nbconvertapp.py", line 252, in NbConvertApp
    Options include {get_export_names()}.
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\nbconvert\exporters\base.py", line 145, in get_export_names
    e = get_exporter(exporter_name)(config=config)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\nbconvert\exporters\base.py", line 106, in get_exporter
    exporter = items[0].load()
               ^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\importlib\metadata\__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\jupyter_contrib_nbextensions\nbconvert_support\__init__.py", line 5, in <module>
    from .collapsible_headings import ExporterCollapsibleHeadings
  File "C:\Users\user\anaconda3\Lib\site-packages\jupyter_contrib_nbextensions\nbconvert_support\collapsible_headings.py", line 6, in <module>
    from notebook.services.config import ConfigManager
ModuleNotFoundError: No module named 'notebook.services'

C:\Users\user\anaconda3\Scripts>
Many thanks in advance,

**Comment by SrinivasanShanmugam1311** [comment]
And also another issue please, when I tried to install "pyppeteer-install" in anconda power shell prompt, I am seeing the below please : https://stackoverflow.com/questions/66514334/nbconvert-use-allow-chromium-download, any advises onto this also would be highly appreciated, many thanks in advance once again

(base) PS C:\Users\user> pyppeteer-install
[INFO] Starting Chromium download.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\anaconda3\Scripts\pyppeteer-install.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\anaconda3\Lib\site-packages\pyppeteer\command.py", line 14, in install
    download_chromium()
  File "C:\Users\user\anaconda3\Lib\site-packages\pyppeteer\chromium_downloader.py", line 138, in download_chromium
    extract_zip(download_zip(get_url()), DOWNLOADS_FOLDER / REVISION)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\pyppeteer\chromium_downloader.py", line 82, in download_zip
    raise OSError(f'Chromium downloadable not found at {url}: ' f'Received {r.data.decode()}.\n')
OSError: Chromium downloadable not found at https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/1181205/chrome-win.zip: Received <?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: chromium-browser-snapshots/Win_x64/1181205/chrome-win.zip</Details></Error>.

(base) PS C:\Users\user>
