### ISSUE TITLE
Installation in docker fails

### ISSUE THREAD

**Issue by larytet** [pyppeteer/pyppeteer#254]
I am using Ubuntu bionic container (18.04)
```
Step 19/29 : RUN python3 -m venv .
 ---> Using cache
 ---> 921d12b1ff09
Step 20/29 : RUN python3 -m pip install setuptools
 ---> Using cache
 ---> 112749c3d9f4
Step 21/29 : RUN python3 -m pip install -U git+https://github.com/pyppeteer/pyppeteer@dev
 ---> Running in d9ff781c3217
Collecting git+https://github.com/pyppeteer/pyppeteer@dev
  Cloning https://github.com/pyppeteer/pyppeteer (to dev) to /tmp/pip-d7qe1_0r-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-d7qe1_0r-build/setup.py'

```

**Comment by larytet** [comment]
Switch to 20.04 update the default pip3 version
See also https://github.com/miyakogi/pyppeteer/issues/14
