### ISSUE TITLE
Adding call to page.screenshot triggers a failure 

### ISSUE THREAD

**Issue by larytet** [pyppeteer/pyppeteer#255]
This is the code https://github.com/larytet-py/headless-chrome/blob/master/src/process_url.py#L258

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyppeteer/launcher.py", line 152, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 591, in run_until_complete
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'Launcher.killChrome' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Connection._recv_loop() running at /usr/local/lib/python3.8/dist-packages/pyppeteer/connection.py:65>>
Exception ignored in: <coroutine object Connection._recv_loop at 0x7f864d87ae40>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyppeteer/connection.py", line 65, in _recv_loop
  File "/usr/local/lib/python3.8/dist-packages/websockets/client.py", line 525, in __aexit__
  File "/usr/local/lib/python3.8/dist-packages/websockets/protocol.py", line 676, in close
  File "/usr/lib/python3.8/asyncio/tasks.py", line 448, in wait_for
RuntimeError: no running event loop
sys:1: RuntimeWarning: coroutine 'WebSocketCommonProtocol.write_close_frame' was never awaited
Task was destroyed but it is pending!
task: <Task pending name='Task-120' coro=<EventHandler.request_interception() running at /home/chrome/src/process_url.py:179> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f864d7aa820>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-123' coro=<EventHandler.request_interception() running at /home/chrome/src/process_url.py:179> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f864d7aa880>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<WebSocketCommonProtocol.transfer_data() running at /usr/local/lib/python3.8/dist-packages/websockets/protocol.py:827> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f864d804af0>()]> cb=[<TaskWakeupMethWrapper object at 0x7f864d87e880>()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<WebSocketCommonProtocol.close_connection() running at /usr/local/lib/python3.8/dist-packages/websockets/protocol.py:1169> wait_for=<Task pending name='Task-4' coro=<WebSocketCommonProtocol.transfer_data() running at /usr/local/lib/python3.8/dist-packages/websockets/protocol.py:827> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f864d804af0>()]> cb=[<TaskWakeupMethWrapper object at 0x7f864d87e880>()]>>
Exception ignored in: <coroutine object WebSocketCommonProtocol.close_connection at 0x7f864d813bc0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/websockets/protocol.py", line 1204, in close_connection
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 690, in close
  File "/usr/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed

```

**Comment by larytet** [comment]
There was a bug in the args of the screenhot() - do not use base64 True
