### ISSUE TITLE
Screenshot fails from some WEB sites

### ISSUE THREAD

**Issue by larytet** [pyppeteer/pyppeteer#257]
```
Traceback (most recent call last):
  File "./src/process_url.py", line 260, in load_page
    self.screenshot = await self._take_screenshot(page)
  File "./src/process_url.py", line 241, in _take_screenshot
    await page.screenshot({"path": filename, "fullPage": True})
  File "/usr/local/lib/python3.8/dist-packages/pyppeteer/page.py", line 1253, in screenshot
    return await self._screenshotTask(screenshotType, options)
  File "/usr/local/lib/python3.8/dist-packages/pyppeteer/page.py", line 1300, in _screenshotTask
    result = await self._client.send('Page.captureScreenshot', opt)
pyppeteer.errors.NetworkError: Protocol error (Page.captureScreenshot): Cannot take screenshot with 0 width.
```

The link is unfortunately a phishing URL. I modify the protocol type just in case 

`hxxp://www.49_13_49.neuss.cl/#aHR0cHM6Ly9ncnlmZmVzcG91bHkuY29tL3RyYXNoL3JxcG1scWtmLmdmdj9naGgwN18xM18wNzQ5MDcwN18wN18xMz1waWFubmlAYmFjYXJkaS5jb20=
`

**Comment by larytet** [comment]
I did not wait enough time before taking a screnshot. This is the fix 
```
            await page.goto(
                url,
                {
                    "timeout": int(self.timeout * 1000),
                    "waitUntil": ["load", "networkidle0"],
                },
            )

```
