### ISSUE TITLE
[E:pyppeteer.connection] connection unexpectedly closed

### ISSUE THREAD

**Issue by tjaycodes4you** [pyppeteer/pyppeteer#261]
Hi guys. I'm trying to scale up my automations with pyppeteer, unfortunately, I keep coming up on this error:

```py
[E:pyppeteer.connection] connection unexpectedly closed
Task exception was never retrieved
future: <Task finished name='Task-49801' coro=<Connection._async_send() done, defined at C:\Program Files\Python39\lib\site-packages\pyppeteer\connection.py:69> exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\websockets\protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "C:\Program Files\Python39\lib\site-packages\websockets\protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "C:\Program Files\Python39\lib\site-packages\websockets\protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "C:\Program Files\Python39\lib\site-packages\websockets\protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "C:\Program Files\Python39\lib\site-packages\websockets\framing.py", line 105, in read
    data = await reader(2)
  File "C:\Program Files\Python39\lib\asyncio\streams.py", line 712, in readexactly
    raise self._exception
  File "C:\Program Files\Python39\lib\asyncio\selector_events.py", line 856, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\pyppeteer\connection.py", line 73, in _async_send
    await self.connection.send(msg)
  File "C:\Program Files\Python39\lib\site-packages\websockets\protocol.py", line 555, in send
    await self.ensure_open()
  File "C:\Program Files\Python39\lib\site-packages\websockets\protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\pyppeteer\connection.py", line 79, in _async_send
    await self.dispose()
  File "C:\Program Files\Python39\lib\site-packages\pyppeteer\connection.py", line 170, in dispose
    await self._on_close()
  File "C:\Program Files\Python39\lib\site-packages\pyppeteer\connection.py", line 151, in _on_close
    cb.set_exception(_rewriteError(
asyncio.exceptions.InvalidStateError: invalid state
```

It's not such a bad error on its own, sometimes the code just keeps going, unfortunately, sometimes, it also just stops. I've written up a mockup code, it's pretty much how I launch my tasks right now anyway:

```py
async def async_run():
    async def run():
        while True:
            browser = await launch()
            page = await browser.pages()
            page = page[0]
            await page.goto('http://api64.ipify.org/')
            await sleep(1)
            await browser.close()
            info('Done')
    num_tasks = 1000
    res = await asyncio.gather(*[run() for _ in range(num_tasks)], return_exceptions=True)
    for r in res:
        print(r)
    return res


if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(async_run())
```

I'm using an Azure server, 128GB ram, so I figure it should be able to take this much damage (1000 tasks, my regular process runs just 100 but runs into the same error.)

This test code runs without any problems, I had it running for about 30 minutes, PyCharm got a bit slow, but other than that, no issues. I don't really know what's wrong with my main task, i'm assuming it's an unexcepted error my code runs into from time to time and I still don't really know how to deal with it. It's been months now, I cannot scale, it sucks.

I've run the popular `patch_pypetter()` fx. I've disabled timeouts and cache. I've excepted the main code runner in my automation class. I don't know what to do. Please, any help at all is appreciated.

**Comment by Ne00n** [comment]
By default it uses Chromium Version 71, from 2018.
After switching to a local installed chromium version with executablePath, I never had a crash ever, again.
