### ISSUE TITLE
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by pradyjswl** [pyppeteer/pyppeteer#284]
Whats the common cause of this error? I get this error intermittently at many place in my code.

```
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\Anaconda3\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

**Comment by nilpotent7** [comment]
Any updates?

**Comment by windu80** [comment]
I had that error popping all the time. In my case, passing the arguments as a dictionary instead of keyword arguments in the methods/functions somehow solved the issue.
