### ISSUE TITLE
AttributeError: module 'websockets' has no attribute 'client'

### ISSUE THREAD

**Issue by ctrl-huangyq** [pyppeteer/pyppeteer#287]
When I was using ```requests_html``` which uses ```pyppeteer```, it printed the traceback below.
```
Traceback (most recent call last):
  File "c:\Users\ctrlh\Documents\Code\<omitted>\get_pages.py", line 5, in <module>
    res.html.render()
  File "C:\Users\ctrlh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests_html.py", line 586, in render
    self.browser = self.session.browser  # Automatically create a event loop and browser
  File "C:\Users\ctrlh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests_html.py", line 730, in browser
    self._browser = self.loop.run_until_complete(super().browser)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\ctrlh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests_html.py", line 714, in browser
    self._browser = await pyppeteer.launch(ignoreHTTPSErrors=not(self.verify), headless=True, args=self.__browser_args)
  File "C:\Users\ctrlh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyppeteer\launcher.py", line 251, in launch
    return await Launcher(options, **kwargs).launch()
  File "C:\Users\ctrlh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyppeteer\launcher.py", line 168, in launch
    self.connection = Connection(self.browserWSEndpoint, connectionDelay)
  File "C:\Users\ctrlh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyppeteer\connection.py", line 39, in __init__
    self._ws = websockets.client.connect(self._url, max_size=None)
  File "C:\Users\ctrlh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\websockets\imports.py", line 96, in __getattr__
    raise AttributeError(f"module {package!r} has no attribute {name!r}")
AttributeError: module 'websockets' has no attribute 'client'
```

I've installed ```websocket-client``` and ```websocket-client-py3``` but it doesn't works.

**Comment by zillionare** [comment]
this is caused by websockets version you have chosen.  According to my test, pyppeteer support websockets up to version 8.1, according to poetry.lock file, version 9.0 is supported though (not work in my test)

Same issue I have experienced, it's gone once I downgrade websockets to 8.1

**Comment by ctrl-huangyq** [comment]
Thanks @zillionare. It works after I installs ```websockets 8.1```.
