### ISSUE TITLE
None of the websocket server is working with pyppeteer

### ISSUE THREAD

**Issue by jitendersaini** [pyppeteer/pyppeteer#290]
I'm trying to send my scrapping progress to UI with help of Websocket server but none of the method is working and throwing same error every time and that is:

**_sys:1: RuntimeWarning: coroutine 'Launcher.killChrome' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Connection._recv_loop() running at /Users/j.saini/python_virtual_envs/web_scraper/lib/python3.8/site-packages/pyppeteer/connection.py:59> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f7f90c60760>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<WebSocketCommonProtocol.transfer_data() running at /Users/j.saini/python_virtual_envs/web_scraper/lib/python3.8/site-packages/websockets/protocol.py:827> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f7f90c32ee0>()]> cb=[<TaskWakeupMethWrapper object at 0x7f7f90b49160>(), _wait.<locals>._on_completion() at /Users/j.saini/python_virtual_envs/web_scraper/lib/python3.8/asyncio/tasks.py:507]>
Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<WebSocketCommonProtocol.close_connection() running at /Users/j.saini/python_virtual_envs/web_scraper/lib/python3.8/site-packages/websockets/protocol.py:1169> wait_for=<Task pending name='Task-4' coro=<WebSocketCommonProtocol.transfer_data() running at /Users/j.saini/python_virtual_envs/web_scraper/lib/python3.8/site-packages/websockets/protocol.py:827> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f7f90c32ee0>()]> cb=[<TaskWakeupMethWrapper object at 0x7f7f90b49160>(), _wait.<locals>._on_completion() at /Users/j.saini/python_virtual_envs/web_scraper/lib/python3.8/asyncio/tasks.py:507]>>
Exception ignored in: <coroutine object Connection._recv_loop at 0x7f7f908f18c0>
Traceback (most recent call last):
  File "/Users/j.saini/python_virtual_envs/web_scraper/lib/python3.8/site-packages/pyppeteer/connection.py", line 65, in _recv_loop
    await asyncio.sleep(0)
  File "/Users/j.saini/python_virtual_envs/web_scraper/lib/python3.8/site-packages/websockets/client.py", line 525, in __aexit__
    await self.ws_client.close()
  File "/Users/j.saini/python_virtual_envs/web_scraper/lib/python3.8/site-packages/websockets/protocol.py", line 676, in close
    await asyncio.wait_for(
  File "/Users/j.saini/python_virtual_envs/web_scraper/lib/python3.8/asyncio/tasks.py", line 448, in wait_for
    loop = events.get_running_loop()
RuntimeError: no running event loop
sys:1: RuntimeWarning: coroutine 'WebSocketCommonProtocol.write_close_frame' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Exception ignored in: <coroutine object WebSocketCommonProtocol.close_connection at 0x7f7f90b672c0>
Traceback (most recent call last):
  File "/Users/j.saini/python_virtual_envs/web_scraper/lib/python3.8/site-packages/websockets/protocol.py", line 1204, in close_connection
    self.transport.close()
  File "/Users/j.saini/python_virtual_envs/web_scraper/lib/python3.8/asyncio/selector_events.py", line 690, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/Users/j.saini/python_virtual_envs/web_scraper/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
    self._check_closed()
  File "/Users/j.saini/python_virtual_envs/web_scraper/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed_**

I'm calling the websocket send method like below:

**self.hello('Hello this is my progress')**

My class is:

**import asyncio, json, time
from pyppeteer import launch
from datetime import datetime
from pymongo import MongoClient
from utilities.CategoryScrape import cat
#from utilities.Ws import hello
import websockets

class ScrapeData:
    def __init__(self):
        print('ScrapeData init called')
        self.arr = []
        self.progress = {}
        self.options = {"waitUntil": 'load', "timeout": 900 * 1000}  # 900 minutes wait time

    @staticmethod
    async def a_second():
        await asyncio.sleep(0.2)

    async def hello(msg):
        uri = "ws://localhost:8765"
        async with websockets.connect(uri) as websocket:            
            await websocket.send(msg)**

**Comment by Mattwmaster58** [comment]
Chrome seems to be crashing, and currently the way we clean up chrome is quite janky. So that will need to be improved.
