### ISSUE TITLE
pyppeteer is not working in headless environment like RHEL or cloud vm etc. 

### ISSUE THREAD

**Issue by jitendersaini** [pyppeteer/pyppeteer#292]
I just checked it in azure vm headless environment it's not launching the web browser even with headless=True. The exception coming for the following code is:

import asyncio
from pyppeteer import launch

async def main():
    browser = await launch(headless=True)
    page = await browser.newPage()
    await page.goto('https://google.com')
    element = await page.querySelector('title')
    title = await page.evaluate('(element) => element.textContent', element)
    print('title is: ', title)
    await browser.close()

asyncio.get_event_loop().run_until_complete(main())

Exception is:

Traceback (most recent call last):
  File "test.py", line 13, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "test.py", line 5, in main
    browser = await launch(headless=True)
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/launcher.py", line 306, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/launcher.py", line 167, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/launcher.py", line 226, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

**Comment by Mattwmaster58** [comment]
Try running the same chrome binary manually, and seeing if it can even launch itself. There could be missing libs at play here.

**Comment by norey** [comment]
@Mattwmaster58 is right, chrome is missing some dependencies. I just installed the required ones on a debian 11 distro

```
apt install libglib2.0-dev libnss3-dev libcups2-dev libxss-dev libasound2-dev libpangocairo-1.0-0 libatk1.0-dev libatk-bridge2.0-dev libgtk-3-dev
```
