### ISSUE TITLE
[URGENT] Pyppeteer not working with --no-console pyinstaller

### ISSUE THREAD

**Issue by jaegyuch** [pyppeteer/pyppeteer#300]
I use the command `pyinstaller --one-file --windowed --copy-metadata pyppeteer SCRIPT.py` in order to get the .exe file. However, this generated .exe file does not work, and I tried implementing a catch exception on the script, and it just seems like it doesn't want to run the function at all.

`async def main():`
    `    try:`
        `~actual code~`
    `    except:`
        `return`
(Sorry about the indenting, I never use github so I don't know how to exactly paste the code in, but indents are fine on my code)

It doesn't go through the code, and just returns an exception. I heard this had to do something with subprocesses -- by using the --windowed option it blocks some of the ability for the subprocess to communicate with the underlying program, causing the crash. Is there a fix for this?

**Comment by Mattwmaster58** [comment]
Based on your description this doesn't necessarily sounds like a pyppeteer error. What's The full traceback of the exception?

**Comment by jaegyuch** [comment]
It says "[WinError 6] The handle is invalid". @Mattwmaster58

**Comment by Mattwmaster58** [comment]
Is that the full traceback?

**Comment by jaegyuch** [comment]
I'm not sure how to get the full traceback, because this issue seems to only show up when I am not using a console... so I'm just going off of what `except Exception as e` and printing `e` onto my tkinter GUI. Is there somehow a way to get the full traceback? And `e` on the GUI just shows "[WinError 6] The handle is invalid"

**Comment by jaegyuch** [comment]
@Mattwmaster58 I found the full traceback.. I'll paste it here:
https://gyazo.com/391e63573420f653e5aeda5b960682fc

`Traceback (most recent call last)`
`File "automate.py", line 45, in main`
`File "pyppeteer\launcher.py", line 306, in launch`
`File "pyppeteer\launcher.py", line 147, in launch`
`File "subprocess.py", line 829, in __init__`
`File "subprocess.py", line 1252, in __get__handles`
`OSError: [WinError 6] The handle is invalid`

**Comment by dmanthing** [comment]
If anyone else is facing this issue, it is related with Pyinstaller disable switch for console. Once you use `--no-console` on Pyinstaller, pyppeteer's `subprocess.Popen()` won't work anymore.

Dirty fix is to edit pyppeteer's `launcher.py` line 148 and replace the `Popen()` with the one without console

```
# self.proc = subprocess.Popen(  # type: ignore
#     self.cmd, **options, )

startupinfo = subprocess.STARTUPINFO()
startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
self.proc = subprocess.Popen(self.cmd, env=self.env, startupinfo=startupinfo, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)
```
