### ISSUE TITLE
Windows 10 new install issues

### ISSUE THREAD

**Issue by nono-london** [pyppeteer/pyppeteer#316]
When running for the first time pyppeteer. Program stops while downloading chromium with error, console logs the bellow for my project called "test":

[W:pyppeteer.chromium_downloader] Starting Chromium download. Download may take a few minutes.

Traceback (most recent call last):

  File "D:\Path8toPythonProject\Projects\Python\test\.venv\lib\site-packages\urllib3\connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "D:\Path8toPythonProject\Projects\Python\test\.venv\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Python\Python379\lib\socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Path8toPythonProject\Projects\Python\test\.venv\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "D:\Path8toPythonProject\Projects\Python\test\.venv\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "D:\Path8toPythonProject\Projects\Python\test\.venv\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "D:\Path8toPythonProject\Projects\Python\test\.venv\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "D:\Path8toPythonProject\Projects\Python\test\.venv\lib\site-packages\urllib3\connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001E82C85B088>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/WindowsFolder/Documents/VisualStudioCode/Projects/Python/test/test_pyppeteer.py", line 14, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Python\Python379\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "D:/WindowsFolder/Documents/VisualStudioCode/Projects/Python/test/test_pyppeteer.py", line 7, in main
    browser = await launch()
  File "D:\Path8toPythonProject\Projects\Python\test\.venv\lib\site-packages\pyppeteer\launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "D:\Path8toPythonProject\Projects\Python\test\.venv\lib\site-packages\pyppeteer\launcher.py", line 120, in __init__
    download_chromium()
  File "D:\Path8toPythonProject\Projects\Python\test\.venv\lib\site-packages\pyppeteer\chromium_downloader.py", line 139, in download_chromium
    extract_zip(download_zip(get_url()), DOWNLOADS_FOLDER / REVISION)
  File "D:\Path8toPythonProject\Projects\Python\test\.venv\lib\site-packages\pyppeteer\chromium_downloader.py", line 81, in download_zip
    r = http.request('GET', url, preload_content=False)
  File "D:\Path8toPythonProject\Projects\Python\test\.venv\lib\site-packages\urllib3\request.py", line 75, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "D:\Path8toPythonProject\Projects\Python\test\.venv\lib\site-packages\urllib3\request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "D:\Path8toPythonProject\Projects\Python\test\.venv\lib\site-packages\urllib3\poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "D:\Path8toPythonProject\Projects\Python\test\.venv\lib\site-packages\urllib3\connectionpool.py", line 796, in urlopen
    **response_kw
  File "D:\Path8toPythonProject\Projects\Python\test\.venv\lib\site-packages\urllib3\connectionpool.py", line 796, in urlopen
    **response_kw
  File "D:\Path8toPythonProject\Projects\Python\test\.venv\lib\site-packages\urllib3\connectionpool.py", line 796, in urlopen
    **response_kw
  File "D:\Path8toPythonProject\Projects\Python\test\.venv\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\Path8toPythonProject\Projects\Python\test\.venv\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /chromium-browser-snapshots/Win_x64/588429/chrome-win32.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E82C85B088>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

.

**Comment by Mattwmaster58** [comment]
> Failed to establish a new connection: [Errno 11001] getaddrinfo failed

The hostname resolution is failing for some reason, and it could be a lot of things. Arguably we should better handle these sorts of errors but this really isn't a pyppeteer issue at heart, this download was going to fail either way and whether it was handled gracefully or not wouldn't change that fact.
