### ISSUE TITLE
certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by eggplants** [pyppeteer/pyppeteer#329]
```shellsession
$ python -V
Python 3.9.7
$ uname -vorm
21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64 Darwin
$ pip install pyppeteer
...
Successfully installed pyppeteer-0.2.6
$ python -c 'from pyppeteer import chromium_downloader as c;c.download_chromium()'
[W:pyppeteer.chromium_downloader] Starting Chromium download. Download may take a few minutes.
Traceback (most recent call last):
  File "/Users/eggplants/.pyenv/versions/3.9.7/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/eggplants/.pyenv/versions/3.9.7/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/eggplants/.pyenv/versions/3.9.7/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/Users/eggplants/.pyenv/versions/3.9.7/lib/python3.9/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/eggplants/.pyenv/versions/3.9.7/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/eggplants/.pyenv/versions/3.9.7/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/eggplants/.pyenv/versions/3.9.7/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/eggplants/.pyenv/versions/3.9.7/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Users/eggplants/.pyenv/versions/3.9.7/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/eggplants/.pyenv/versions/3.9.7/lib/python3.9/site-packages/pyppeteer/chromium_downloader.py", line 139, in download_chromium
    extract_zip(download_zip(get_url()), DOWNLOADS_FOLDER / REVISION)
  File "/Users/eggplants/.pyenv/versions/3.9.7/lib/python3.9/site-packages/pyppeteer/chromium_downloader.py", line 81, in download_zip
    r = http.request('GET', url, preload_content=False)
  File "/Users/eggplants/.pyenv/versions/3.9.7/lib/python3.9/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/Users/eggplants/.pyenv/versions/3.9.7/lib/python3.9/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/Users/eggplants/.pyenv/versions/3.9.7/lib/python3.9/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/eggplants/.pyenv/versions/3.9.7/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/Users/eggplants/.pyenv/versions/3.9.7/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/Users/eggplants/.pyenv/versions/3.9.7/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/Users/eggplants/.pyenv/versions/3.9.7/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/eggplants/.pyenv/versions/3.9.7/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /chromium-browser-snapshots/Mac/588429/chrome-mac.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
$
```

**Comment by eggplants** [comment]
ref: #105
```shellsession
$ export PYPPETEER_DOWNLOAD_HOST='http://storage.googleapis.com'
$ python -c 'from pyppeteer import chromium_downloader as c;c.download_chromium()'
[W:pyppeteer.chromium_downloader] Starting Chromium download. Download may take a few minutes.
100%|████████████████████████████████████████████████████████████████████████████████████| 86.8M/86.8M [00:15<00:00, 5.59Mb/s]
[W:pyppeteer.chromium_downloader] Chromium download done.
[W:pyppeteer.chromium_downloader] chromium extracted to: /Users/eggplants/Library/Application Support/pyppeteer/local-chromium/588429
$ 
```
