### ISSUE TITLE
Circular Import Error in fresh venv

### ISSUE THREAD

**Issue by lkirkwood** [pyppeteer/pyppeteer#344]
When importing pyppeteer at all on my Ubuntu 21.10 system I recieve a circular import error as seen below. This is in a fresh virtualenv using Python 3.9.7.
```
Traceback (most recent call last):                                                                                     
  File "/home/linus/tmp/test.py", line 1, in <module>                                                                  
    import pyppeteer                                                                                                   
  File "/home/linus/.virtualenvs/test/lib/python3.9/site-packages/pyppeteer/__init__.py", line 10, in <module>         
    from pyppeteer.launcher import connect, executablePath, launch                                                     
  File "/home/linus/.virtualenvs/test/lib/python3.9/site-packages/pyppeteer/launcher.py", line 25, in <module>         
    from pyppeteer import __pyppeteer_home__                                                                           
ImportError: cannot import name '__pyppeteer_home__' from partially initialized module 'pyppeteer' (most likely due to 
a circular import) (/home/linus/.virtualenvs/test/lib/python3.9/site-packages/pyppeteer/__init__.py)
```

**Comment by kickononnell** [comment]
I've also run into this issue while trying to use requests_html (I am not actually importing pyppeteer directly). For reference, I'm on Windows 11 with Python 3.10.1. Seems like there is no way around this bug atm.

**Comment by JackieFei** [comment]
+1, Python 3.8.8 on Mac
```
ImportError: cannot import name '__pyppeteer_home__' from partially initialized module 'pyppeteer' (most likely due to a circular import)
```

**Comment by Mattwmaster58** [comment]
I'll take a look into this tonight. Does this occur in 1.0.0? I don't recall changing anything major and I thought I did test 1.0.1

**Comment by Mattwmaster58** [comment]
Pushed 1.0.2 to fix this
