### ISSUE TITLE
Title: Test fail.  

### ISSUE THREAD

**Issue by odidev** [pyppeteer/pyppeteer#375]
I have been working to build and test this package for amd64 and arm64 architectures. While testing this package with “tox” getting errors for **poetry install** command for both architectures, it is failed to install m2r (0.2.1) and showing the below error. 

**Error:** 
```
Command ['/pyppeteer/venv38/bin/pip', 'install', '--no-deps', 'file:///root/.cache/pypoetry/artifacts/4f/27/1c/8c4108008bcf8c4bb68f981912836a9bdefd1e6b91408a2291566af273/m2r-0.2.1.tar.gz'] errored with the following return code 1, and output: 

  Processing /root/.cache/pypoetry/artifacts/4f/27/1c/8c4108008bcf8c4bb68f981912836a9bdefd1e6b91408a2291566af273/m2r-0.2.1.tar.gz 

    Preparing metadata (setup.py): started 

    Preparing metadata (setup.py): finished with status 'error' 

    error: subprocess-exited-with-error 

    × python setup.py egg_info did not run successfully. 

    │ exit code: 1 

    ╰─> [8 lines of output] 

        Traceback (most recent call last): 

          File "<string>", line 2, in <module> 

          File "<pip-setuptools-caller>", line 34, in <module> 

          File "/tmp/pip-req-build-q_b8pahy/setup.py", line 14, in <module> 

            from m2r import parse_from_file 

          File "/tmp/pip-req-build-q_b8pahy/m2r.py", line 59, in <module> 

            class RestBlockGrammar(mistune.BlockGrammar): 

        AttributeError: module 'mistune' has no attribute 'BlockGrammar' 

        [end of output] 

    note: This error originates from a subprocess and is likely not a problem with pip. 

  error: metadata-generation-failed 
``` 

- I followed this [issue](https://github.com/Tribler/tribler/issues/6624#issue-1072155143) and changed the mistune version from 2.0.0 to 0.8.4, now getting the RuntimeError for mistune. 

- Got another  [issue](https://github.com/miyakogi/m2r/issues/66#issuecomment-988617920) for m2r it looks like this repository is not being maintained anymore. 

-  Also Installed m2r using “apt-get -y install m2r” command, it is installed successfully m2r (0.2.1-3), edit the m2r version mention in poetry.lock file (0.2.1 to 0.2.1-3) it is showing RuntimeError: 

`Error: Unable to find installation candidates for m2r (0.2.1-3)` 

**Error Log for your reference:**  [pyppeteer_test_result.txt](https://github.com/pyppeteer/pyppeteer/files/8423754/pyppeteer_test_result.txt)

Could you please provide your feedback regarding this.

**Comment by odidev** [comment]
Is there any update for the above issue?

**Comment by Mattwmaster58** [comment]
m2r looks like a docs thing. There's not enough time for any of the maintainers right now to fix this sort of thing, to try and get it to work I'd try just removing the dependancy. Just building the package shouldn't require it. I think

**Comment by odidev** [comment]
@Mattwmaster58 thanks for your response, 

Still getting the same issue for poetry install command, could you please remove m2r dependency.
