### ISSUE TITLE
1.0.2: sphinx is failing

### ISSUE THREAD

**Issue by kloczek** [pyppeteer/pyppeteer#385]
Looks like sphinx is failing on generate documentation
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v4.5.0

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/pyppeteer-1.0.2/docs/conf.py", line 34, in <module>
    import pyppeteer
  File "/home/tkloczko/rpmbuild/BUILD/pyppeteer-1.0.2/pyppeteer/__init__.py", line 33, in <module>
    version_info = tuple(int(i) for i in version.split('.'))
AttributeError: 'NoneType' object has no attribute 'split'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 165, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 345, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/pyppeteer-1.0.2/docs/conf.py", line 34, in <module>
    import pyppeteer
  File "/home/tkloczko/rpmbuild/BUILD/pyppeteer-1.0.2/pyppeteer/__init__.py", line 33, in <module>
    version_info = tuple(int(i) for i in version.split('.'))
AttributeError: 'NoneType' object has no attribute 'split'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/pyppeteer-1.0.2/docs/conf.py", line 34, in <module>
    import pyppeteer
  File "/home/tkloczko/rpmbuild/BUILD/pyppeteer-1.0.2/pyppeteer/__init__.py", line 33, in <module>
    version_info = tuple(int(i) for i in version.split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by kloczek** [comment]
gentle ping ..

**Comment by Mattwmaster58** [comment]
Sorry for the delay in general. This project is effectively unmaintained at the moment.

**Comment by kloczek** [comment]
So are you lookimg for new maintainer?
If yes I woud suggest to drop comment in every still opened PR that you are looking for new maintainer and/or add in project description that you are lookimg for new maintainer.

**Comment by Mattwmaster58** [comment]
Yes, I agree

**Comment by kloczek** [comment]
IMO you should add info about that on top of the README or in project description.
