### ISSUE TITLE
NewPage hangs indefinitely even in the simplest docker container

### ISSUE THREAD

**Issue by stasbel** [pyppeteer/pyppeteer#395]
Steps to reporoduce:

1. **Dockerfile**

```
FROM --platform=linux/amd64 python:3.10

# Taken from CI
RUN apt update && apt install -yq \
    ca-certificates fonts-liberation libasound2 libatk1.0-0 \
    libcairo2 libcups2 libdbus-1-3 libgdk-pixbuf2.0-0 \
    libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 \
    libpangocairo-1.0-0 libx11-xcb1 libxcomposite1 libxcursor1 \
    libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
    lsb-release xdg-utils wget 

RUN pip install pyppeteer

ADD pypp_test.py .

CMD python pypp_test.py
```

2. **pypp_test.py**

```python
import asyncio

from pyppeteer import launch


async def main():
    print('1')
    browser = await launch(
        headless=True,
        args=['--no-sandbox'],
    )
    print('2')
    page = await browser.newPage()
    print('3')
    await page.goto('https://example.com')
    print('4')
    await page.screenshot({'path': 'example.png'})
    print('5')
    await browser.close()
    print('6')


asyncio.get_event_loop().run_until_complete(main())
```

3. **commands**

```
docker build Dockerfile -t pypp .
docker run --platform=linux/amd64 --rm pypp
```
...is never priting all 1-6 numbers, most likely just 1, occasionally 1-2.

However, it doest work just fine on host M1 Macbook.

**Comment by velkyvont** [comment]
I have exactly the same issue. A script is running as expected on my Ubuntu laptop but when copied to my Ubuntu VPS, it just stalls on page = await browser.newPage()

**Comment by codeScriber** [comment]
i'm still in stages of installing all missing dependencies for starting chrome or chromium properly in a docker. (using ldd on the executable). However did any of you guys checked if running chromiuim with --headless works inside the docker ?

**Comment by bolsen** [comment]
I am running Ubuntu 22.04, so whatever libraries are on there, it might be related. I did not test this in a Docker instance.

However, I did an install today and saw the same problem:

 * From `pip list`: `pyppeteer          1.0.2`
 *  `$ /home/bolsen/.local/share/pyppeteer/local-chromium/588429/chrome-linux/chrome --version`
       `Chromium 71.0.3542.0`
 * When I tested the second example in the README ("Evaluate javascript on a page"), it would hang on newPage(). Seeing what it was coming up in the browser, I got an "Aww, Snap!" error page. However, I couldn't see why it was doing this because the browser was not allowing me to navigate.
 * I changed `browser = await launch()` to be `await launch(headless=False, executablePath="/usr/bin/google-chrome")`. The `headless` was just to get a confirmation.
 
I am not sure if there is anything specific with docker here, but this is what I found. I checked this in Python 3.8 and 3.10 for a version comparison and see that the Python version is not relevant here.

**Comment by rbkprod** [comment]
Using the same config as @stasbel - on amd64 my container just seem to hang when the command is run, if I switch to arm64 I actually get an error:

```python
Traceback (most recent call last):
  File "//pt.py", line 16, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "//pt.py", line 6, in main
    browser = await launch(
  File "/usr/local/lib/python3.10/site-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.10/site-packages/pyppeteer/launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/usr/local/lib/python3.10/site-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:
```

Dockerfile:

```dockerfile
# syntax=docker/dockerfile:1
FROM --platform=linux/amd64 python:3.10

# Taken from CI
RUN apt update && apt install -yq \
    ca-certificates fonts-liberation libasound2 libatk1.0-0 \
    libcairo2 libcups2 libdbus-1-3 libgdk-pixbuf2.0-0 \
    libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 \
    libpangocairo-1.0-0 libx11-xcb1 libxcomposite1 libxcursor1 \
    libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
    lsb-release xdg-utils wget 

RUN pip install pyppeteer

ADD pt.py .

CMD python pt.py
```

pt.py:

```python
import asyncio
from pyppeteer import launch


async def main():
    browser = await launch(
        headless=True,
        args=["--no-sandbox"],
    )
    page = await browser.newPage()
    await page.goto("https://example.com")
    await page.screenshot({"path": "example.png"})
    await browser.close()


asyncio.get_event_loop().run_until_complete(main())

```

As with posters above, it all works 100% on my local machine, just not in Docker.

**Comment by jw-star** [comment]
[ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.5/dumb-init_1.2.5_x86_64 /usr/local/bin/dumb-init](https://github.com/jw-star/91pornBot/blob/825f5525407651f84f105ebc39174a0560c5e303/Dockerfile#L9)
https://github.com/jw-star/91pornBot/blob/825f5525407651f84f105ebc39174a0560c5e303/Dockerfile#L10

You can add the following command to your dockerfile

**Comment by INSIinc** [comment]
> I am running Ubuntu 22.04, so whatever libraries are on there, it might be related. I did not test this in a Docker instance.
> 
> However, I did an install today and saw the same problem:
> 
> * From `pip list`: `pyppeteer          1.0.2`
> * `$ /home/bolsen/.local/share/pyppeteer/local-chromium/588429/chrome-linux/chrome --version`
>   `Chromium 71.0.3542.0`
> * When I tested the second example in the README ("Evaluate javascript on a page"), it would hang on newPage(). Seeing what it was coming up in the browser, I got an "Aww, Snap!" error page. However, I couldn't see why it was doing this because the browser was not allowing me to navigate.
> * I changed `browser = await launch()` to be `await launch(headless=False, executablePath="/usr/bin/google-chrome")`. The `headless` was just to get a confirmation.
> 
> I am not sure if there is anything specific with docker here, but this is what I found. I checked this in Python 3.8 and 3.10 for a version comparison and see that the Python version is not relevant here.

completely same with you,and i am using ubuntu 22.04
