### ISSUE TITLE
BrowserError: Browser closed unexpectedly

### ISSUE THREAD

**Issue by jaan143** [pyppeteer/pyppeteer#406]
i am trying to conver html to pdf file but getting this error 
i cannot find windows os solution on internet kindly help me to solve out it.

D:\pp\downloader.py:183: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(html2pdf())
Traceback (most recent call last):
  File "D:\pp\downloader.py", line 183, in <module>
    asyncio.get_event_loop().run_until_complete(html2pdf())
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\pp\downloader.py", line 114, in html2pdf
    browser = await launch(options={
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

PS D:\pp>

**Comment by rahulbanwasi** [comment]
did you got any fix for the same?

**Comment by jaan143** [comment]
@rahulbanwasi yes i got fixed.
