### ISSUE TITLE
launch error

### ISSUE THREAD

**Issue by qaz862220184** [pyppeteer/pyppeteer#417]
import asyncio
from pyppeteer import launch

async def main():
    browser = await launch()
    page = await browser.newPage()
    await page.goto('http://example.com')
    await page.screenshot({'path': 'example.png'})
    await browser.close()

asyncio.get_event_loop().run_until_complete(main())

error：
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\pythonProject\test.py", line 11, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 484, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\PycharmProjects\pythonProject\test.py", line 5, in main
    browser = await launch()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pyppeteer\launcher.py", line 306, in launch
    return await Launcher(options, **kwargs).launch()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pyppeteer\launcher.py", line 167, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pyppeteer\launcher.py", line 229, in get_ws_endpoint
    data = json.loads(f.read().decode())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1

**Comment by runningabcd** [comment]
一看你就是国人，兄弟多看看 doc吧
