### ISSUE TITLE
websockets ConnectionClosedError

### ISSUE THREAD

**Issue by ViktorRubenko** [pyppeteer/pyppeteer#422]
I'm facing with this issue during async multipage parsing

```
future: <Task finished name='Task-21526' coro=<Connection._async_send() done, defined at /home/tt/scripts/env/lib/python3.10/site-packages/pyppeteer/connection.py:69> exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
  File "/home/tt/scripts/env/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 945, in transfer_data
    message = await self.read_message()
  File "/home/tt/scripts/env/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1015, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/tt/scripts/env/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1090, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/tt/scripts/env/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1145, in read_frame
    frame = await Frame.read(
  File "/home/tt/scripts/env/lib/python3.10/site-packages/websockets/legacy/framing.py", line 70, in read
    data = await reader(2)
  File "/usr/lib/python3.10/asyncio/streams.py", line 706, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tt/scripts/env/lib/python3.10/site-packages/pyppeteer/connection.py", line 73, in _async_send
    await self.connection.send(msg)
  File "/home/tt/scripts/env/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 620, in send
    await self.ensure_open()
  File "/home/tt/scripts/env/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 921, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tt/scripts/env/lib/python3.10/site-packages/pyppeteer/connection.py", line 79, in _async_send
    await self.dispose()
  File "/home/tt/scripts/env/lib/python3.10/site-packages/pyppeteer/connection.py", line 170, in dispose
    await self._on_close()
  File "/home/tt/scripts/env/lib/python3.10/site-packages/pyppeteer/connection.py", line 151, in _on_close
    cb.set_exception(_rewriteError(
asyncio.exceptions.InvalidStateError: invalid state
```
then this
```
future: <Task finished name='Task-21525' coro=<pypParser._fetch() done, defined at /home/tt/scripts/fontParser/pypParser.py:155> exception=AttributeError("'NoneType' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/home/tt/scripts/fontParser/pypParser.py", line 109, in _fetch_fonts
    page = await browser.newPage()
  File "/home/tt/scripts/env/lib/python3.10/site-packages/pyppeteer/browser.py", line 202, in newPage
    return await self._defaultContext.newPage()
  File "/home/tt/scripts/env/lib/python3.10/site-packages/pyppeteer/browser.py", line 358, in newPage
    return await self._browser._createPageInContext(self._id)
  File "/home/tt/scripts/env/lib/python3.10/site-packages/pyppeteer/browser.py", line 210, in _createPageInContext
    'Target.createTarget', options)).get('targetId')
AttributeError: 'NoneType' object has no attribute 'get
```

and for every newPage this:
```
future: <Task finished name='Task-21542' coro=<pypParser._fetch() done, defined at /home/tt/scripts/fontParser/pypParser.py:155> exception=ConnectionError('Connection is closed')>
Traceback (most recent call last):
  File "/home/tt/scripts/fontParser/pypParser.py", line 109, in _fetch_fonts
    page = await browser.newPage()
  File "/home/tt/scripts/env/lib/python3.10/site-packages/pyppeteer/browser.py", line 202, in newPage
    return await self._defaultContext.newPage()
  File "/home/tt/scripts/env/lib/python3.10/site-packages/pyppeteer/browser.py", line 358, in newPage
    return await self._browser._createPageInContext(self._id)
  File "/home/tt/scripts/env/lib/python3.10/site-packages/pyppeteer/browser.py", line 209, in _createPageInContext
    targetId = (await self._connection.send(
  File "/home/tt/scripts/env/lib/python3.10/site-packages/pyppeteer/connection.py", line 85, in send
    raise ConnectionError('Connection is closed')
ConnectionError: Connection is closed
```
how can I handle this?

**Comment by ViktorRubenko** [comment]
The problem was in auth window on page load.

Fix:
```
await page.authenticate({})
```
