### ISSUE TITLE
Can't run pyppeteer with Threads? - ValueError: signal only works in main thread of the main interpreter

### ISSUE THREAD

**Issue by FuckingToasters** [pyppeteer/pyppeteer#424]
```py
Exception in thread Thread-1 (verify):
Traceback (most recent call last):
  File "D:\Downloads\Projects\testproject\new version\plugins\captcha\hcaptchasolver.py", line 108, in _getHsw
    browser = await pyppeteer.launch({"headless": self.headless, 'executablePath': chrome, "userDataDir": self.userDataPath, "args": []})
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyppeteer\launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyppeteer\launcher.py", line 159, in launch
    signal.signal(signal.SIGINT, _close_process)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
```

**Comment by jingjingxyk** [comment]
`pyppeteer` connection chrome/chromium use   [DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/). 

reference https://github.com/aslushnikov/getting-started-with-cdp/blob/master/README.md
```
    browser = await pyppeteer.launch({"headless": self.headless, 'executablePath': chrome, "userDataDir": self.userDataPath, "args": []})
```
@FuckingToasters 

You can use multithreading on `browser`  object .
