### ISSUE TITLE
linux pyppeteer error

### ISSUE THREAD

**Issue by 674514904** [pyppeteer/pyppeteer#427]
Only in Linux error

588429
/root/.local/share/pyppeteer/local-chromium/588429/chrome-linux/chrome
Traceback (most recent call last):
  File "/py_project/agri-price-lyga/test1.py", line 40, in <module>
    asyncio.get_event_loop().run_until_complete(main()) #调用
  File "/root/anaconda3/envs/pachong/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/py_project/agri-price-lyga/test1.py", line 26, in main
    browser = await launch(headless=True,options={'args': ['—-no-sandbox']})
  File "/root/anaconda3/envs/pachong/lib/python3.8/site-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "/root/anaconda3/envs/pachong/lib/python3.8/site-packages/pyppeteer/launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/root/anaconda3/envs/pachong/lib/python3.8/site-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

**Comment by 674514904** [comment]
This is my code

import asyncio, time
from pyppeteer import launch
import pyppeteer

print(pyppeteer.__chromium_revision__)  # 查看版本号
print(pyppeteer.executablePath())  # Chromium应该在的路径
import pyppeteer.chromium_downloader
# 这里的 linux 替换成你系统的版本，win32，win64，linux
# 这个是返回在当前系统下chromium的路径
# print(pyppeteer.chromium_downloader.chromiumExecutable.get("linux"))
# # 这个是返回当前系统默认的下载地址
# print(pyppeteer.chromium_downloader.downloadURLs.get("linux"))
# exit()

async def main():
    browser = await launch(headless=True,options={'args': ['—-no-sandbox']})
    page = await browser.newPage()           # 打开新的标签页
    await page.setViewport({'width': 1920, 'height': 1080})      # 页面大小一致
    await page.goto('https://www.baidu.com') # 访问主页

    # evaluate()是执行js的方法，js逆向时如果需要在浏览器环境下执行js代码的话可以利用这个方法
    # js为设置webdriver的值，防止网站检测
    await page.evaluate('''() =>{ Object.defineProperties(navigator,{ webdriver:{ get: () => false } }) }''')
    # await page.screenshot({'path': './1.jpg'})   # 截图保存路径

    page_text = await page.content()   # 获取网页源码
    print(page_text)
    time.sleep(1)
    await page.close()
asyncio.get_event_loop().run_until_complete(main()) #调用

**Comment by 674514904** [comment]
##

import asyncio, time
from pyppeteer import launch
import pyppeteer

print(pyppeteer.__chromium_revision__)  # 查看版本号
print(pyppeteer.executablePath())  # Chromium应该在的路径
import pyppeteer.chromium_downloader
# 这里的 linux 替换成你系统的版本，win32，win64，linux
# 这个是返回在当前系统下chromium的路径
# print(pyppeteer.chromium_downloader.chromiumExecutable.get("linux"))
# # 这个是返回当前系统默认的下载地址
# print(pyppeteer.chromium_downloader.downloadURLs.get("linux"))
# exit()

async def main():
    browser = await launch(headless=True,options={'args': ['—-no-sandbox']})
    page = await browser.newPage()           # 打开新的标签页
    await page.setViewport({'width': 1920, 'height': 1080})      # 页面大小一致
    await page.goto('https://www.baidu.com') # 访问主页

    # evaluate()是执行js的方法，js逆向时如果需要在浏览器环境下执行js代码的话可以利用这个方法
    # js为设置webdriver的值，防止网站检测
    await page.evaluate('''() =>{ Object.defineProperties(navigator,{ webdriver:{ get: () => false } }) }''')
    # await page.screenshot({'path': './1.jpg'})   # 截图保存路径

    page_text = await page.content()   # 获取网页源码
    print(page_text)
    time.sleep(1)
    await page.close()
asyncio.get_event_loop().run_until_complete(main()) #调用

##
