### ISSUE TITLE
pyppeteer Browser closed unexpectedly

### ISSUE THREAD

**Issue by MominIqbal-1234** [pyppeteer/pyppeteer#442]
i use Linux machine  and chromium install sucessfully 
when i run script so return this error

My Code:

import asyncio
from pyppeteer import launch

async def scrape_website(url):
    browser = await launch()
    page = await browser.newPage()
    await page.goto(url)
    html_content = await page.content()
    # await browser.close()
    return html_content

# URL of the website you want to scrape
website_url = 'https://example.com/'

# Run the scraping function
html_content = asyncio.get_event_loop().run_until_complete(scrape_website(website_url))

# Print the HTML content
print(html_content)

Traceback (most recent call last):
  File "/pythoncode/main.py", line 16, in <module>
    html_content = asyncio.get_event_loop().run_until_complete(scrape_website(website_url))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/pythoncode/main.py", line 5, in scrape_website
    browser = await launch()
  File "/usr/local/lib/python3.10/dist-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.10/dist-packages/pyppeteer/launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/usr/local/lib/python3.10/dist-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

**Comment by sergeyyurkov1** [comment]
This error usually indicates missing dependencies. Try installing `libxtst6` with `apt` or your distribution's equivalent. Check if anything else is missing by running the following command: `ldd /root/.local/share/pyppeteer/local-chromium/588429/chrome-linux/chrome | grep "not found"` (the path on your machine may differ). Additionally, you may need to pass `args=["--no-sandbox"]` argument to the `await launch()` function.

**Comment by akul-goyal** [comment]
I tried all of the suggestions made by @sergeyyurkov1  but I am still getting a Browser closed unexpectedly error running the same code as the original poster

**Comment by sergeyyurkov1** [comment]
Although Pyppeteer guys don't recommend this approach because of possible version incompatibilities, you can try the following:

1. Install `chromium-browser` (Ubuntu) or `chromium` (Debian) with `apt` or equivalent
2. Locate Chromium executable with `whereis chromium` and copy the first path you see
3. Pass `executablePath="YOUR PATH"` into the `launch` function

Tested on Debian Buster.

**Comment by kdudyala** [comment]
Hi Team
I am also facing same issue. I have passed additional arguments to launch function.
browser = await launch(headless=True, 
                               args=['--no-sandbox', '--disable-dev-shm-usage', '--disable-gpu', '--disable-software-rasterizer', '--disable-setuid-sandbox'])
 In local I am not facing same issue but when we deploy it the issue occurs continuously. Please suggest.

**Comment by GregKarabinos** [comment]
I am facing this issue as well.  It is a big blocker for me.

**Comment by shindi-renuo** [comment]
Also facing this issue.
