### ISSUE TITLE
Pyppeteer v2.0.0 first run Chromium downloadable

### ISSUE THREAD

**Issue by Cuikenn** [pyppeteer/pyppeteer#472]
> [INFO] Starting Chromium download.
Traceback (most recent call last):
  File "E:\PycharmProjects\pp\ppp.py", line 20, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\pc\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "E:\PycharmProjects\pp\ppp.py", line 11, in main
    browser = await launch() # 启动浏览器
  File "E:\PycharmProjects\pp\.venv\lib\site-packages\pyppeteer\launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "E:\PycharmProjects\pp\.venv\lib\site-packages\pyppeteer\launcher.py", line 120, in __init__
    download_chromium()
  File "E:\PycharmProjects\pp\.venv\lib\site-packages\pyppeteer\chromium_downloader.py", line 138, in download_chromium
    extract_zip(download_zip(get_url()), DOWNLOADS_FOLDER / REVISION)
  File "E:\PycharmProjects\pp\.venv\lib\site-packages\pyppeteer\chromium_downloader.py", line 82, in download_zip
    raise OSError(f'Chromium downloadable not found at {url}: ' f'Received {r.data.decode()}.\n')
OSError: Chromium downloadable not found at https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/1181205/chrome-win.zip: Received <?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: chromium-browser-snapshots/Win_x64/1181205/chrome-win.zip</Details></Error>.

I try to visit this url: https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/1181205/chrome-win.zip
But it's not found.Please check the chromium version 1181205 is exist.

**Comment by J4RF** [comment]
The package enforces a specific Chromium revision for no good reason, and in this release it's a revision that doesn't exist for Windows. Well done folks...

You can manually download the latest Chromium revision for Windows (.zip) here: https://chromium.woolyss.com/download/en/, then create a folder called 1181205 in C:\Users\<username>\AppData\Local\pyppeteer\pyppeteer\local-chromium\, and drag the extracted chrome-win folder into the 1181205 folder.

**Comment by Alashmony** [comment]
I changed the chrome downloader on my windows as follows: 

`DOWNLOADS_FOLDER = Path(__pyppeteer_home__) / 'local-chromium'
DEFAULT_DOWNLOAD_HOST = 'https://www.googleapis.com'
DOWNLOAD_HOST = os.environ.get('PYPPETEER_DOWNLOAD_HOST', DEFAULT_DOWNLOAD_HOST)
BASE_URL = f'{DOWNLOAD_HOST}/storage/v1/b/chromium-browser-snapshots/o'

REVISION = os.environ.get('PYPPETEER_CHROMIUM_REVISION', __chromium_revision__)

NO_PROGRESS_BAR = os.environ.get('PYPPETEER_NO_PROGRESS_BAR', '')
if NO_PROGRESS_BAR.lower() in ('1', 'true'):
    NO_PROGRESS_BAR = True  # type: ignore

windowsArchive = 'chrome-win'

downloadURLs = {
    'linux': f'{BASE_URL}/Linux_x64/{REVISION}/chrome-linux.zip',
    'mac': f'{BASE_URL}/Mac/{REVISION}/chrome-mac.zip',
    'win32': f'{BASE_URL}/Win/{REVISION}/{windowsArchive}.zip',
    #'win64': f'{BASE_URL}/Win_x64/{REVISION}/{windowsArchive}.zip',
    'win64' : f'{BASE_URL}/Win_x64%2F1304219%2F{windowsArchive}.zip?alt=media',

}
`

**Comment by BenMcLean** [comment]
My personal solution to this has been to just use [PuppeteerSharp](https://github.com/hardkoded/puppeteer-sharp) on Windows instead.

> The package enforces a specific Chromium revision for no good reason, and in this release it's a revision that doesn't exist for Windows. Well done folks...

If that is true then it should be actually fixed in the code, not just worked around for Windows users, don't you think?

(later edit) It appears that pyppeteer is unmaintained as per #1.

**Comment by bityob** [comment]
Simple workaround is to use env variable 
```
set PYPPETEER_CHROMIUM_REVISION=1304219
uv run --with pyppeteer python -c "import asyncio; from pyppeteer import launch; asyncio.run(launch())"
```

![Image](https://github.com/user-attachments/assets/b705371a-03f0-45c4-8cf8-2e183c29ece6)

**Comment by jsomeara** [comment]
> Simple workaround is to use env variable
> 
> ```
> set PYPPETEER_CHROMIUM_REVISION=1304219
> uv run --with pyppeteer python -c "import asyncio; from pyppeteer import launch; asyncio.run(launch())"
> ```
> 
> ![Image](https://github.com/user-attachments/assets/b705371a-03f0-45c4-8cf8-2e183c29ece6)

thanks!!!

I ended up putting this at the top of my file:

```
import os
os.environ["PYPPETEER_CHROMIUM_REVISION"] = "1304219"
```
