### ISSUE TITLE
Error: Protocol error (Page.navigate): Target closed.

### ISSUE THREAD

**Issue by CircleHeSG** [pyppeteer/pyppeteer#481]
After applied the below server patches in Red Hat 8.5, we found that the **Puppeteer** reported an error "error: Error: Protocol error (Page.navigate): Target closed." 

`error: Protocol error (Page.navigate): Target closed. {"timestamp":"2024-02-08T13:55:35.822Z"}
error: Error: Protocol error (Page.navigate): Target closed.
    at /oracle/psft/nodejs/OChartExport/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (/oracle/psft/nodejs/OChartExport/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/Connection.js:182:12)
    at navigate (/oracle/psft/nodejs/OChartExport/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/FrameManager.js:118:39)
    at FrameManager.navigateFrame (/oracle/psft/nodejs/OChartExport/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/FrameManager.js:95:7)
    at Frame.goto (/oracle/psft/nodejs/OChartExport/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/FrameManager.js:406:37)
    at Frame.<anonymous> (/oracle/psft/nodejs/OChartExport/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.goto (/oracle/psft/nodejs/OChartExport/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/oracle/psft/nodejs/OChartExport/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/helper.js:112:23)
    at /oracle/psft/nodejs/OChartExport/node_modules/@balkangraph/export-service/export3.js:65:24
  -- ASYNC --
    at Frame.<anonymous> (/oracle/psft/nodejs/OChartExport/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/oracle/psft/nodejs/OChartExport/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/oracle/psft/nodejs/OChartExport/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/helper.js:112:23)
    at /oracle/psft/nodejs/OChartExport/node_modules/@balkangraph/export-service/export3.js:65:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {"timestamp":"2024-02-08T13:55:35.822Z"}`

Puppeteer: v22.8.1
.local-chromium: linux-1284446
NodeJs: v20.13.1

These patches are kernel, python3, sqlite, gnutls, pixman, libxml2 or GConf2.

Packages Altered:
    Install       kernel-4.18.0-513.18.1.el8_9.x86_64               @rhel-8-for-x86_64-baseos-rpms
    Install       kernel-core-4.18.0-513.18.1.el8_9.x86_64          @rhel-8-for-x86_64-baseos-rpms
    Install       kernel-modules-4.18.0-513.18.1.el8_9.x86_64       @rhel-8-for-x86_64-baseos-rpms
    Upgrade       pixman-0.38.4-3.el8_9.x86_64                      @rhel-8-for-x86_64-appstream-rpms
    Upgraded      pixman-0.38.4-2.el8.x86_64                        @@System
    Upgrade       gnutls-c++-3.6.16-8.el8_9.1.x86_64                @rhel-8-for-x86_64-appstream-rpms
    Upgraded      gnutls-c++-3.6.16-6.el8_7.x86_64                  @@System
    Upgrade       gnutls-dane-3.6.16-8.el8_9.1.x86_64               @rhel-8-for-x86_64-appstream-rpms
    Upgraded      gnutls-dane-3.6.16-6.el8_7.x86_64                 @@System
    Upgrade       gnutls-devel-3.6.16-8.el8_9.1.x86_64              @rhel-8-for-x86_64-appstream-rpms
    Upgraded      gnutls-devel-3.6.16-6.el8_7.x86_64                @@System
    Upgrade       gnutls-utils-3.6.16-8.el8_9.1.x86_64              @rhel-8-for-x86_64-appstream-rpms
    Upgraded      gnutls-utils-3.6.16-6.el8_7.x86_64                @@System
    Upgrade       libmaxminddb-1.2.0-10.el8_9.1.x86_64              @rhel-8-for-x86_64-appstream-rpms
    Upgraded      libmaxminddb-1.2.0-10.el8.x86_64                  @@System
    Upgrade       nss-softokn-freebl-3.90.0-6.el8_9.x86_64          @rhel-8-for-x86_64-appstream-rpms
    Upgraded      nss-softokn-freebl-3.79.0-11.el8_7.x86_64         @@System
    Upgrade       python3-unbound-1.16.2-5.el8_9.2.x86_64           @rhel-8-for-x86_64-appstream-rpms
    Upgraded      python3-unbound-1.16.2-5.el8.x86_64               @@System
    Upgrade       unbound-libs-1.16.2-5.el8_9.2.x86_64              @rhel-8-for-x86_64-appstream-rpms
    Upgraded      unbound-libs-1.16.2-5.el8.x86_64                  @@System
    Upgrade       libxml2-2.9.7-18.el8_9.x86_64                     @rhel-8-for-x86_64-baseos-rpms
    Upgraded      libxml2-2.9.7-16.el8_8.1.x86_64                   @@System
    Upgrade       platform-python-3.6.8-56.el8_9.3.x86_64           @rhel-8-for-x86_64-baseos-rpms
    Upgraded      platform-python-3.6.8-56.el8_9.x86_64             @@System
    Upgrade       python3-libs-3.6.8-56.el8_9.3.x86_64              @rhel-8-for-x86_64-baseos-rpms
    Upgraded      python3-libs-3.6.8-56.el8_9.x86_64                @@System
    Upgrade       python3-libxml2-2.9.7-18.el8_9.x86_64             @rhel-8-for-x86_64-baseos-rpms
    Upgraded      python3-libxml2-2.9.7-16.el8_8.1.x86_64           @@System
    Upgrade       python3-urllib3-1.24.2-5.el8_9.2.noarch           @rhel-8-for-x86_64-baseos-rpms
    Upgraded      python3-urllib3-1.24.2-5.el8.noarch               @@System
    Upgrade       sqlite-3.26.0-19.el8_9.x86_64                     @rhel-8-for-x86_64-baseos-rpms
    Upgraded      sqlite-3.26.0-18.el8_8.x86_64                     @@System
    Upgrade       sqlite-libs-3.26.0-19.el8_9.x86_64                @rhel-8-for-x86_64-baseos-rpms
    Upgraded      sqlite-libs-3.26.0-18.el8_8.x86_64                @@System
    Upgrade       openssh-8.0p1-19.el8_9.2.x86_64                   @rhel-8-for-x86_64-baseos-rpms
    Upgraded      openssh-8.0p1-19.el8_8.x86_64                     @@System
    Upgrade       openssh-clients-8.0p1-19.el8_9.2.x86_64           @rhel-8-for-x86_64-baseos-rpms
    Upgraded      openssh-clients-8.0p1-19.el8_8.x86_64             @@System
    Upgrade       openssh-server-8.0p1-19.el8_9.2.x86_64            @rhel-8-for-x86_64-baseos-rpms
    Upgraded      openssh-server-8.0p1-19.el8_8.x86_64              @@System
    Upgrade       gnutls-3.6.16-8.el8_9.1.x86_64                    @rhel-8-for-x86_64-baseos-rpms
    Upgraded      gnutls-3.6.16-6.el8_7.x86_64                      @@System
    Upgrade       libssh-0.9.6-13.el8_9.x86_64                      @rhel-8-for-x86_64-baseos-rpms
    Upgraded      libssh-0.9.6-10.el8_8.x86_64                      @@System
    Upgrade       libssh-config-0.9.6-13.el8_9.noarch               @rhel-8-for-x86_64-baseos-rpms
    Upgraded      libssh-config-0.9.6-10.el8_8.noarch               @@System
    Upgrade       python3-rpm-4.14.3-28.el8_9.x86_64                @rhel-8-for-x86_64-baseos-rpms
    Upgraded      python3-rpm-4.14.3-24.el8_7.x86_64                @@System
    Upgrade       rpm-4.14.3-28.el8_9.x86_64                        @rhel-8-for-x86_64-baseos-rpms
    Upgraded      rpm-4.14.3-24.el8_7.x86_64                        @@System
    Upgrade       rpm-build-libs-4.14.3-28.el8_9.x86_64             @rhel-8-for-x86_64-baseos-rpms
    Upgraded      rpm-build-libs-4.14.3-24.el8_7.x86_64             @@System
    Upgrade       rpm-libs-4.14.3-28.el8_9.x86_64                   @rhel-8-for-x86_64-baseos-rpms
    Upgraded      rpm-libs-4.14.3-24.el8_7.x86_64                   @@System
    Upgrade       rpm-plugin-selinux-4.14.3-28.el8_9.x86_64         @rhel-8-for-x86_64-baseos-rpms
    Upgraded      rpm-plugin-selinux-4.14.3-24.el8_7.x86_64         @@System
    Upgrade       rpm-plugin-systemd-inhibit-4.14.3-28.el8_9.x86_64 @rhel-8-for-x86_64-baseos-rpms
    Upgraded      rpm-plugin-systemd-inhibit-4.14.3-24.el8_7.x86_64 @@System
    Upgrade       sudo-1.9.5p2-1.el8_9.x86_64                       @rhel-8-for-x86_64-baseos-rpms
    Upgraded      sudo-1.8.29-8.el8_7.1.x86_64                      @@System
    Upgrade       kernel-headers-4.18.0-513.18.1.el8_9.x86_64       @rhel-8-for-x86_64-baseos-rpms
    Upgraded      kernel-headers-4.18.0-513.9.1.el8_9.x86_64        @@System
    Upgrade       kernel-tools-4.18.0-513.18.1.el8_9.x86_64         @rhel-8-for-x86_64-baseos-rpms
    Upgraded      kernel-tools-4.18.0-513.9.1.el8_9.x86_64          @@System
    Upgrade       kernel-tools-libs-4.18.0-513.18.1.el8_9.x86_64    @rhel-8-for-x86_64-baseos-rpms
    Upgraded      kernel-tools-libs-4.18.0-513.9.1.el8_9.x86_64     @@System
    Upgrade       python3-perf-4.18.0-513.18.1.el8_9.x86_64         @rhel-8-for-x86_64-baseos-rpms
    Upgraded      python3-perf-4.18.0-513.9.1.el8_9.x86_64          @@System
    Reason Change GConf2-3.2.6-22.el8.x86_64                        @rhel-8-for-x86_64-appstream-rpms
    Removed       kernel-4.18.0-477.27.1.el8_8.x86_64               @@System
    Removed       kernel-core-4.18.0-477.27.1.el8_8.x86_64          @@System
    Removed       kernel-modules-4.18.0-477.27.1.el8_8.x86_64       @@System

**Comment by CircleHeSG** [comment]
According to our test, upgrading nss-softokn-freebl alone caused the Chromium to report an error.
We have fixed this issue via manually executing 'yum update nss*', FYI.
